// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client2gate.proto

package com.wangboo.cluster.protocol;

public final class Client2GateProto {
  private Client2GateProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface C2G_LoginMsgOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string username = 1;
    boolean hasUsername();
    String getUsername();
    
    // required string password = 2;
    boolean hasPassword();
    String getPassword();
    
    // required int32 channel = 3;
    boolean hasChannel();
    int getChannel();
  }
  public static final class C2G_LoginMsg extends
      com.google.protobuf.GeneratedMessage
      implements C2G_LoginMsgOrBuilder {
    // Use C2G_LoginMsg.newBuilder() to construct.
    private C2G_LoginMsg(Builder builder) {
      super(builder);
    }
    private C2G_LoginMsg(boolean noInit) {}
    
    private static final C2G_LoginMsg defaultInstance;
    public static C2G_LoginMsg getDefaultInstance() {
      return defaultInstance;
    }
    
    public C2G_LoginMsg getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.wangboo.cluster.protocol.Client2GateProto.internal_static_C2G_LoginMsg_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.wangboo.cluster.protocol.Client2GateProto.internal_static_C2G_LoginMsg_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string username = 1;
    public static final int USERNAME_FIELD_NUMBER = 1;
    private java.lang.Object username_;
    public boolean hasUsername() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getUsername() {
      java.lang.Object ref = username_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          username_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getUsernameBytes() {
      java.lang.Object ref = username_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        username_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string password = 2;
    public static final int PASSWORD_FIELD_NUMBER = 2;
    private java.lang.Object password_;
    public boolean hasPassword() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getPassword() {
      java.lang.Object ref = password_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          password_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getPasswordBytes() {
      java.lang.Object ref = password_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        password_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required int32 channel = 3;
    public static final int CHANNEL_FIELD_NUMBER = 3;
    private int channel_;
    public boolean hasChannel() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public int getChannel() {
      return channel_;
    }
    
    private void initFields() {
      username_ = "";
      password_ = "";
      channel_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasUsername()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPassword()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasChannel()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getUsernameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getPasswordBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, channel_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getUsernameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getPasswordBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, channel_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.wangboo.cluster.protocol.Client2GateProto.C2G_LoginMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.wangboo.cluster.protocol.Client2GateProto.C2G_LoginMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.wangboo.cluster.protocol.Client2GateProto.C2G_LoginMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.wangboo.cluster.protocol.Client2GateProto.C2G_LoginMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.wangboo.cluster.protocol.Client2GateProto.C2G_LoginMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.wangboo.cluster.protocol.Client2GateProto.C2G_LoginMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.wangboo.cluster.protocol.Client2GateProto.C2G_LoginMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.wangboo.cluster.protocol.Client2GateProto.C2G_LoginMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.wangboo.cluster.protocol.Client2GateProto.C2G_LoginMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.wangboo.cluster.protocol.Client2GateProto.C2G_LoginMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.wangboo.cluster.protocol.Client2GateProto.C2G_LoginMsg prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.wangboo.cluster.protocol.Client2GateProto.C2G_LoginMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.wangboo.cluster.protocol.Client2GateProto.internal_static_C2G_LoginMsg_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.wangboo.cluster.protocol.Client2GateProto.internal_static_C2G_LoginMsg_fieldAccessorTable;
      }
      
      // Construct using com.wangboo.cluster.protocol.Client2GateProto.C2G_LoginMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        username_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        password_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        channel_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.wangboo.cluster.protocol.Client2GateProto.C2G_LoginMsg.getDescriptor();
      }
      
      public com.wangboo.cluster.protocol.Client2GateProto.C2G_LoginMsg getDefaultInstanceForType() {
        return com.wangboo.cluster.protocol.Client2GateProto.C2G_LoginMsg.getDefaultInstance();
      }
      
      public com.wangboo.cluster.protocol.Client2GateProto.C2G_LoginMsg build() {
        com.wangboo.cluster.protocol.Client2GateProto.C2G_LoginMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.wangboo.cluster.protocol.Client2GateProto.C2G_LoginMsg buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.wangboo.cluster.protocol.Client2GateProto.C2G_LoginMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.wangboo.cluster.protocol.Client2GateProto.C2G_LoginMsg buildPartial() {
        com.wangboo.cluster.protocol.Client2GateProto.C2G_LoginMsg result = new com.wangboo.cluster.protocol.Client2GateProto.C2G_LoginMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.username_ = username_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.password_ = password_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.channel_ = channel_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.wangboo.cluster.protocol.Client2GateProto.C2G_LoginMsg) {
          return mergeFrom((com.wangboo.cluster.protocol.Client2GateProto.C2G_LoginMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.wangboo.cluster.protocol.Client2GateProto.C2G_LoginMsg other) {
        if (other == com.wangboo.cluster.protocol.Client2GateProto.C2G_LoginMsg.getDefaultInstance()) return this;
        if (other.hasUsername()) {
          setUsername(other.getUsername());
        }
        if (other.hasPassword()) {
          setPassword(other.getPassword());
        }
        if (other.hasChannel()) {
          setChannel(other.getChannel());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasUsername()) {
          
          return false;
        }
        if (!hasPassword()) {
          
          return false;
        }
        if (!hasChannel()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              username_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              password_ = input.readBytes();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              channel_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string username = 1;
      private java.lang.Object username_ = "";
      public boolean hasUsername() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getUsername() {
        java.lang.Object ref = username_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          username_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setUsername(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        username_ = value;
        onChanged();
        return this;
      }
      public Builder clearUsername() {
        bitField0_ = (bitField0_ & ~0x00000001);
        username_ = getDefaultInstance().getUsername();
        onChanged();
        return this;
      }
      void setUsername(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        username_ = value;
        onChanged();
      }
      
      // required string password = 2;
      private java.lang.Object password_ = "";
      public boolean hasPassword() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getPassword() {
        java.lang.Object ref = password_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          password_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setPassword(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        password_ = value;
        onChanged();
        return this;
      }
      public Builder clearPassword() {
        bitField0_ = (bitField0_ & ~0x00000002);
        password_ = getDefaultInstance().getPassword();
        onChanged();
        return this;
      }
      void setPassword(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        password_ = value;
        onChanged();
      }
      
      // required int32 channel = 3;
      private int channel_ ;
      public boolean hasChannel() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getChannel() {
        return channel_;
      }
      public Builder setChannel(int value) {
        bitField0_ |= 0x00000004;
        channel_ = value;
        onChanged();
        return this;
      }
      public Builder clearChannel() {
        bitField0_ = (bitField0_ & ~0x00000004);
        channel_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:C2G_LoginMsg)
    }
    
    static {
      defaultInstance = new C2G_LoginMsg(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:C2G_LoginMsg)
  }
  
  public interface Client2GateMsgOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required .MsgId msgId = 1;
    boolean hasMsgId();
    com.wangboo.cluster.protocol.MsgIdProto.MsgId getMsgId();
    
    // optional .C2G_LoginMsg loginMsg = 10;
    boolean hasLoginMsg();
    com.wangboo.cluster.protocol.Client2GateProto.C2G_LoginMsg getLoginMsg();
    com.wangboo.cluster.protocol.Client2GateProto.C2G_LoginMsgOrBuilder getLoginMsgOrBuilder();
  }
  public static final class Client2GateMsg extends
      com.google.protobuf.GeneratedMessage
      implements Client2GateMsgOrBuilder {
    // Use Client2GateMsg.newBuilder() to construct.
    private Client2GateMsg(Builder builder) {
      super(builder);
    }
    private Client2GateMsg(boolean noInit) {}
    
    private static final Client2GateMsg defaultInstance;
    public static Client2GateMsg getDefaultInstance() {
      return defaultInstance;
    }
    
    public Client2GateMsg getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.wangboo.cluster.protocol.Client2GateProto.internal_static_Client2GateMsg_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.wangboo.cluster.protocol.Client2GateProto.internal_static_Client2GateMsg_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required .MsgId msgId = 1;
    public static final int MSGID_FIELD_NUMBER = 1;
    private com.wangboo.cluster.protocol.MsgIdProto.MsgId msgId_;
    public boolean hasMsgId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public com.wangboo.cluster.protocol.MsgIdProto.MsgId getMsgId() {
      return msgId_;
    }
    
    // optional .C2G_LoginMsg loginMsg = 10;
    public static final int LOGINMSG_FIELD_NUMBER = 10;
    private com.wangboo.cluster.protocol.Client2GateProto.C2G_LoginMsg loginMsg_;
    public boolean hasLoginMsg() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public com.wangboo.cluster.protocol.Client2GateProto.C2G_LoginMsg getLoginMsg() {
      return loginMsg_;
    }
    public com.wangboo.cluster.protocol.Client2GateProto.C2G_LoginMsgOrBuilder getLoginMsgOrBuilder() {
      return loginMsg_;
    }
    
    private void initFields() {
      msgId_ = com.wangboo.cluster.protocol.MsgIdProto.MsgId.Common_HeartBeat;
      loginMsg_ = com.wangboo.cluster.protocol.Client2GateProto.C2G_LoginMsg.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasMsgId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasLoginMsg()) {
        if (!getLoginMsg().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, msgId_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(10, loginMsg_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, msgId_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(10, loginMsg_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.wangboo.cluster.protocol.Client2GateProto.Client2GateMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.wangboo.cluster.protocol.Client2GateProto.Client2GateMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.wangboo.cluster.protocol.Client2GateProto.Client2GateMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.wangboo.cluster.protocol.Client2GateProto.Client2GateMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.wangboo.cluster.protocol.Client2GateProto.Client2GateMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.wangboo.cluster.protocol.Client2GateProto.Client2GateMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.wangboo.cluster.protocol.Client2GateProto.Client2GateMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.wangboo.cluster.protocol.Client2GateProto.Client2GateMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.wangboo.cluster.protocol.Client2GateProto.Client2GateMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.wangboo.cluster.protocol.Client2GateProto.Client2GateMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.wangboo.cluster.protocol.Client2GateProto.Client2GateMsg prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.wangboo.cluster.protocol.Client2GateProto.Client2GateMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.wangboo.cluster.protocol.Client2GateProto.internal_static_Client2GateMsg_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.wangboo.cluster.protocol.Client2GateProto.internal_static_Client2GateMsg_fieldAccessorTable;
      }
      
      // Construct using com.wangboo.cluster.protocol.Client2GateProto.Client2GateMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getLoginMsgFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        msgId_ = com.wangboo.cluster.protocol.MsgIdProto.MsgId.Common_HeartBeat;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (loginMsgBuilder_ == null) {
          loginMsg_ = com.wangboo.cluster.protocol.Client2GateProto.C2G_LoginMsg.getDefaultInstance();
        } else {
          loginMsgBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.wangboo.cluster.protocol.Client2GateProto.Client2GateMsg.getDescriptor();
      }
      
      public com.wangboo.cluster.protocol.Client2GateProto.Client2GateMsg getDefaultInstanceForType() {
        return com.wangboo.cluster.protocol.Client2GateProto.Client2GateMsg.getDefaultInstance();
      }
      
      public com.wangboo.cluster.protocol.Client2GateProto.Client2GateMsg build() {
        com.wangboo.cluster.protocol.Client2GateProto.Client2GateMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.wangboo.cluster.protocol.Client2GateProto.Client2GateMsg buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.wangboo.cluster.protocol.Client2GateProto.Client2GateMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.wangboo.cluster.protocol.Client2GateProto.Client2GateMsg buildPartial() {
        com.wangboo.cluster.protocol.Client2GateProto.Client2GateMsg result = new com.wangboo.cluster.protocol.Client2GateProto.Client2GateMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.msgId_ = msgId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (loginMsgBuilder_ == null) {
          result.loginMsg_ = loginMsg_;
        } else {
          result.loginMsg_ = loginMsgBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.wangboo.cluster.protocol.Client2GateProto.Client2GateMsg) {
          return mergeFrom((com.wangboo.cluster.protocol.Client2GateProto.Client2GateMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.wangboo.cluster.protocol.Client2GateProto.Client2GateMsg other) {
        if (other == com.wangboo.cluster.protocol.Client2GateProto.Client2GateMsg.getDefaultInstance()) return this;
        if (other.hasMsgId()) {
          setMsgId(other.getMsgId());
        }
        if (other.hasLoginMsg()) {
          mergeLoginMsg(other.getLoginMsg());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasMsgId()) {
          
          return false;
        }
        if (hasLoginMsg()) {
          if (!getLoginMsg().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.wangboo.cluster.protocol.MsgIdProto.MsgId value = com.wangboo.cluster.protocol.MsgIdProto.MsgId.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                msgId_ = value;
              }
              break;
            }
            case 82: {
              com.wangboo.cluster.protocol.Client2GateProto.C2G_LoginMsg.Builder subBuilder = com.wangboo.cluster.protocol.Client2GateProto.C2G_LoginMsg.newBuilder();
              if (hasLoginMsg()) {
                subBuilder.mergeFrom(getLoginMsg());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setLoginMsg(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required .MsgId msgId = 1;
      private com.wangboo.cluster.protocol.MsgIdProto.MsgId msgId_ = com.wangboo.cluster.protocol.MsgIdProto.MsgId.Common_HeartBeat;
      public boolean hasMsgId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public com.wangboo.cluster.protocol.MsgIdProto.MsgId getMsgId() {
        return msgId_;
      }
      public Builder setMsgId(com.wangboo.cluster.protocol.MsgIdProto.MsgId value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        msgId_ = value;
        onChanged();
        return this;
      }
      public Builder clearMsgId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        msgId_ = com.wangboo.cluster.protocol.MsgIdProto.MsgId.Common_HeartBeat;
        onChanged();
        return this;
      }
      
      // optional .C2G_LoginMsg loginMsg = 10;
      private com.wangboo.cluster.protocol.Client2GateProto.C2G_LoginMsg loginMsg_ = com.wangboo.cluster.protocol.Client2GateProto.C2G_LoginMsg.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.wangboo.cluster.protocol.Client2GateProto.C2G_LoginMsg, com.wangboo.cluster.protocol.Client2GateProto.C2G_LoginMsg.Builder, com.wangboo.cluster.protocol.Client2GateProto.C2G_LoginMsgOrBuilder> loginMsgBuilder_;
      public boolean hasLoginMsg() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public com.wangboo.cluster.protocol.Client2GateProto.C2G_LoginMsg getLoginMsg() {
        if (loginMsgBuilder_ == null) {
          return loginMsg_;
        } else {
          return loginMsgBuilder_.getMessage();
        }
      }
      public Builder setLoginMsg(com.wangboo.cluster.protocol.Client2GateProto.C2G_LoginMsg value) {
        if (loginMsgBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          loginMsg_ = value;
          onChanged();
        } else {
          loginMsgBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder setLoginMsg(
          com.wangboo.cluster.protocol.Client2GateProto.C2G_LoginMsg.Builder builderForValue) {
        if (loginMsgBuilder_ == null) {
          loginMsg_ = builderForValue.build();
          onChanged();
        } else {
          loginMsgBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder mergeLoginMsg(com.wangboo.cluster.protocol.Client2GateProto.C2G_LoginMsg value) {
        if (loginMsgBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              loginMsg_ != com.wangboo.cluster.protocol.Client2GateProto.C2G_LoginMsg.getDefaultInstance()) {
            loginMsg_ =
              com.wangboo.cluster.protocol.Client2GateProto.C2G_LoginMsg.newBuilder(loginMsg_).mergeFrom(value).buildPartial();
          } else {
            loginMsg_ = value;
          }
          onChanged();
        } else {
          loginMsgBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder clearLoginMsg() {
        if (loginMsgBuilder_ == null) {
          loginMsg_ = com.wangboo.cluster.protocol.Client2GateProto.C2G_LoginMsg.getDefaultInstance();
          onChanged();
        } else {
          loginMsgBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      public com.wangboo.cluster.protocol.Client2GateProto.C2G_LoginMsg.Builder getLoginMsgBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getLoginMsgFieldBuilder().getBuilder();
      }
      public com.wangboo.cluster.protocol.Client2GateProto.C2G_LoginMsgOrBuilder getLoginMsgOrBuilder() {
        if (loginMsgBuilder_ != null) {
          return loginMsgBuilder_.getMessageOrBuilder();
        } else {
          return loginMsg_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          com.wangboo.cluster.protocol.Client2GateProto.C2G_LoginMsg, com.wangboo.cluster.protocol.Client2GateProto.C2G_LoginMsg.Builder, com.wangboo.cluster.protocol.Client2GateProto.C2G_LoginMsgOrBuilder> 
          getLoginMsgFieldBuilder() {
        if (loginMsgBuilder_ == null) {
          loginMsgBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.wangboo.cluster.protocol.Client2GateProto.C2G_LoginMsg, com.wangboo.cluster.protocol.Client2GateProto.C2G_LoginMsg.Builder, com.wangboo.cluster.protocol.Client2GateProto.C2G_LoginMsgOrBuilder>(
                  loginMsg_,
                  getParentForChildren(),
                  isClean());
          loginMsg_ = null;
        }
        return loginMsgBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:Client2GateMsg)
    }
    
    static {
      defaultInstance = new Client2GateMsg(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:Client2GateMsg)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_C2G_LoginMsg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_C2G_LoginMsg_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Client2GateMsg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Client2GateMsg_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021client2gate.proto\032\013msgid.proto\"C\n\014C2G_" +
      "LoginMsg\022\020\n\010username\030\001 \002(\t\022\020\n\010password\030\002" +
      " \002(\t\022\017\n\007channel\030\003 \002(\005\"H\n\016Client2GateMsg\022" +
      "\025\n\005msgId\030\001 \002(\0162\006.MsgId\022\037\n\010loginMsg\030\n \001(\013" +
      "2\r.C2G_LoginMsgB0\n\034com.wangboo.cluster.p" +
      "rotocolB\020Client2GateProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_C2G_LoginMsg_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_C2G_LoginMsg_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_C2G_LoginMsg_descriptor,
              new java.lang.String[] { "Username", "Password", "Channel", },
              com.wangboo.cluster.protocol.Client2GateProto.C2G_LoginMsg.class,
              com.wangboo.cluster.protocol.Client2GateProto.C2G_LoginMsg.Builder.class);
          internal_static_Client2GateMsg_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_Client2GateMsg_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Client2GateMsg_descriptor,
              new java.lang.String[] { "MsgId", "LoginMsg", },
              com.wangboo.cluster.protocol.Client2GateProto.Client2GateMsg.class,
              com.wangboo.cluster.protocol.Client2GateProto.Client2GateMsg.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.wangboo.cluster.protocol.MsgIdProto.getDescriptor(),
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
