// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gate2client.proto

package com.wangboo.cluster.protocol;

public final class Gate2ClientProto {
  private Gate2ClientProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface G2C_LoginRespOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string token = 1;
    boolean hasToken();
    String getToken();
  }
  public static final class G2C_LoginResp extends
      com.google.protobuf.GeneratedMessage
      implements G2C_LoginRespOrBuilder {
    // Use G2C_LoginResp.newBuilder() to construct.
    private G2C_LoginResp(Builder builder) {
      super(builder);
    }
    private G2C_LoginResp(boolean noInit) {}
    
    private static final G2C_LoginResp defaultInstance;
    public static G2C_LoginResp getDefaultInstance() {
      return defaultInstance;
    }
    
    public G2C_LoginResp getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.wangboo.cluster.protocol.Gate2ClientProto.internal_static_G2C_LoginResp_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.wangboo.cluster.protocol.Gate2ClientProto.internal_static_G2C_LoginResp_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string token = 1;
    public static final int TOKEN_FIELD_NUMBER = 1;
    private java.lang.Object token_;
    public boolean hasToken() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getToken() {
      java.lang.Object ref = token_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          token_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getTokenBytes() {
      java.lang.Object ref = token_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        token_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      token_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasToken()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getTokenBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getTokenBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.wangboo.cluster.protocol.Gate2ClientProto.G2C_LoginResp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.wangboo.cluster.protocol.Gate2ClientProto.G2C_LoginResp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.wangboo.cluster.protocol.Gate2ClientProto.G2C_LoginResp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.wangboo.cluster.protocol.Gate2ClientProto.G2C_LoginResp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.wangboo.cluster.protocol.Gate2ClientProto.G2C_LoginResp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.wangboo.cluster.protocol.Gate2ClientProto.G2C_LoginResp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.wangboo.cluster.protocol.Gate2ClientProto.G2C_LoginResp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.wangboo.cluster.protocol.Gate2ClientProto.G2C_LoginResp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.wangboo.cluster.protocol.Gate2ClientProto.G2C_LoginResp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.wangboo.cluster.protocol.Gate2ClientProto.G2C_LoginResp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.wangboo.cluster.protocol.Gate2ClientProto.G2C_LoginResp prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.wangboo.cluster.protocol.Gate2ClientProto.G2C_LoginRespOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.wangboo.cluster.protocol.Gate2ClientProto.internal_static_G2C_LoginResp_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.wangboo.cluster.protocol.Gate2ClientProto.internal_static_G2C_LoginResp_fieldAccessorTable;
      }
      
      // Construct using com.wangboo.cluster.protocol.Gate2ClientProto.G2C_LoginResp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        token_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.wangboo.cluster.protocol.Gate2ClientProto.G2C_LoginResp.getDescriptor();
      }
      
      public com.wangboo.cluster.protocol.Gate2ClientProto.G2C_LoginResp getDefaultInstanceForType() {
        return com.wangboo.cluster.protocol.Gate2ClientProto.G2C_LoginResp.getDefaultInstance();
      }
      
      public com.wangboo.cluster.protocol.Gate2ClientProto.G2C_LoginResp build() {
        com.wangboo.cluster.protocol.Gate2ClientProto.G2C_LoginResp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.wangboo.cluster.protocol.Gate2ClientProto.G2C_LoginResp buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.wangboo.cluster.protocol.Gate2ClientProto.G2C_LoginResp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.wangboo.cluster.protocol.Gate2ClientProto.G2C_LoginResp buildPartial() {
        com.wangboo.cluster.protocol.Gate2ClientProto.G2C_LoginResp result = new com.wangboo.cluster.protocol.Gate2ClientProto.G2C_LoginResp(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.token_ = token_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.wangboo.cluster.protocol.Gate2ClientProto.G2C_LoginResp) {
          return mergeFrom((com.wangboo.cluster.protocol.Gate2ClientProto.G2C_LoginResp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.wangboo.cluster.protocol.Gate2ClientProto.G2C_LoginResp other) {
        if (other == com.wangboo.cluster.protocol.Gate2ClientProto.G2C_LoginResp.getDefaultInstance()) return this;
        if (other.hasToken()) {
          setToken(other.getToken());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasToken()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              token_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string token = 1;
      private java.lang.Object token_ = "";
      public boolean hasToken() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getToken() {
        java.lang.Object ref = token_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          token_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setToken(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        token_ = value;
        onChanged();
        return this;
      }
      public Builder clearToken() {
        bitField0_ = (bitField0_ & ~0x00000001);
        token_ = getDefaultInstance().getToken();
        onChanged();
        return this;
      }
      void setToken(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        token_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:G2C_LoginResp)
    }
    
    static {
      defaultInstance = new G2C_LoginResp(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:G2C_LoginResp)
  }
  
  public interface G2C_TalkOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string msg = 1;
    boolean hasMsg();
    String getMsg();
    
    // required int64 fromId = 2;
    boolean hasFromId();
    long getFromId();
    
    // required string fromName = 3;
    boolean hasFromName();
    String getFromName();
  }
  public static final class G2C_Talk extends
      com.google.protobuf.GeneratedMessage
      implements G2C_TalkOrBuilder {
    // Use G2C_Talk.newBuilder() to construct.
    private G2C_Talk(Builder builder) {
      super(builder);
    }
    private G2C_Talk(boolean noInit) {}
    
    private static final G2C_Talk defaultInstance;
    public static G2C_Talk getDefaultInstance() {
      return defaultInstance;
    }
    
    public G2C_Talk getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.wangboo.cluster.protocol.Gate2ClientProto.internal_static_G2C_Talk_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.wangboo.cluster.protocol.Gate2ClientProto.internal_static_G2C_Talk_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string msg = 1;
    public static final int MSG_FIELD_NUMBER = 1;
    private java.lang.Object msg_;
    public boolean hasMsg() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getMsg() {
      java.lang.Object ref = msg_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          msg_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getMsgBytes() {
      java.lang.Object ref = msg_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        msg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required int64 fromId = 2;
    public static final int FROMID_FIELD_NUMBER = 2;
    private long fromId_;
    public boolean hasFromId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public long getFromId() {
      return fromId_;
    }
    
    // required string fromName = 3;
    public static final int FROMNAME_FIELD_NUMBER = 3;
    private java.lang.Object fromName_;
    public boolean hasFromName() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getFromName() {
      java.lang.Object ref = fromName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          fromName_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getFromNameBytes() {
      java.lang.Object ref = fromName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        fromName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      msg_ = "";
      fromId_ = 0L;
      fromName_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasMsg()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasFromId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasFromName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getMsgBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, fromId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getFromNameBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getMsgBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, fromId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getFromNameBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.wangboo.cluster.protocol.Gate2ClientProto.G2C_Talk parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.wangboo.cluster.protocol.Gate2ClientProto.G2C_Talk parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.wangboo.cluster.protocol.Gate2ClientProto.G2C_Talk parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.wangboo.cluster.protocol.Gate2ClientProto.G2C_Talk parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.wangboo.cluster.protocol.Gate2ClientProto.G2C_Talk parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.wangboo.cluster.protocol.Gate2ClientProto.G2C_Talk parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.wangboo.cluster.protocol.Gate2ClientProto.G2C_Talk parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.wangboo.cluster.protocol.Gate2ClientProto.G2C_Talk parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.wangboo.cluster.protocol.Gate2ClientProto.G2C_Talk parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.wangboo.cluster.protocol.Gate2ClientProto.G2C_Talk parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.wangboo.cluster.protocol.Gate2ClientProto.G2C_Talk prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.wangboo.cluster.protocol.Gate2ClientProto.G2C_TalkOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.wangboo.cluster.protocol.Gate2ClientProto.internal_static_G2C_Talk_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.wangboo.cluster.protocol.Gate2ClientProto.internal_static_G2C_Talk_fieldAccessorTable;
      }
      
      // Construct using com.wangboo.cluster.protocol.Gate2ClientProto.G2C_Talk.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        msg_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        fromId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        fromName_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.wangboo.cluster.protocol.Gate2ClientProto.G2C_Talk.getDescriptor();
      }
      
      public com.wangboo.cluster.protocol.Gate2ClientProto.G2C_Talk getDefaultInstanceForType() {
        return com.wangboo.cluster.protocol.Gate2ClientProto.G2C_Talk.getDefaultInstance();
      }
      
      public com.wangboo.cluster.protocol.Gate2ClientProto.G2C_Talk build() {
        com.wangboo.cluster.protocol.Gate2ClientProto.G2C_Talk result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.wangboo.cluster.protocol.Gate2ClientProto.G2C_Talk buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.wangboo.cluster.protocol.Gate2ClientProto.G2C_Talk result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.wangboo.cluster.protocol.Gate2ClientProto.G2C_Talk buildPartial() {
        com.wangboo.cluster.protocol.Gate2ClientProto.G2C_Talk result = new com.wangboo.cluster.protocol.Gate2ClientProto.G2C_Talk(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.msg_ = msg_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.fromId_ = fromId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.fromName_ = fromName_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.wangboo.cluster.protocol.Gate2ClientProto.G2C_Talk) {
          return mergeFrom((com.wangboo.cluster.protocol.Gate2ClientProto.G2C_Talk)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.wangboo.cluster.protocol.Gate2ClientProto.G2C_Talk other) {
        if (other == com.wangboo.cluster.protocol.Gate2ClientProto.G2C_Talk.getDefaultInstance()) return this;
        if (other.hasMsg()) {
          setMsg(other.getMsg());
        }
        if (other.hasFromId()) {
          setFromId(other.getFromId());
        }
        if (other.hasFromName()) {
          setFromName(other.getFromName());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasMsg()) {
          
          return false;
        }
        if (!hasFromId()) {
          
          return false;
        }
        if (!hasFromName()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              msg_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              fromId_ = input.readInt64();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              fromName_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string msg = 1;
      private java.lang.Object msg_ = "";
      public boolean hasMsg() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getMsg() {
        java.lang.Object ref = msg_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          msg_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setMsg(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        msg_ = value;
        onChanged();
        return this;
      }
      public Builder clearMsg() {
        bitField0_ = (bitField0_ & ~0x00000001);
        msg_ = getDefaultInstance().getMsg();
        onChanged();
        return this;
      }
      void setMsg(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        msg_ = value;
        onChanged();
      }
      
      // required int64 fromId = 2;
      private long fromId_ ;
      public boolean hasFromId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public long getFromId() {
        return fromId_;
      }
      public Builder setFromId(long value) {
        bitField0_ |= 0x00000002;
        fromId_ = value;
        onChanged();
        return this;
      }
      public Builder clearFromId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        fromId_ = 0L;
        onChanged();
        return this;
      }
      
      // required string fromName = 3;
      private java.lang.Object fromName_ = "";
      public boolean hasFromName() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getFromName() {
        java.lang.Object ref = fromName_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          fromName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setFromName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        fromName_ = value;
        onChanged();
        return this;
      }
      public Builder clearFromName() {
        bitField0_ = (bitField0_ & ~0x00000004);
        fromName_ = getDefaultInstance().getFromName();
        onChanged();
        return this;
      }
      void setFromName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        fromName_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:G2C_Talk)
    }
    
    static {
      defaultInstance = new G2C_Talk(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:G2C_Talk)
  }
  
  public interface Gate2ClientMsgOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required .MsgId msgId = 1;
    boolean hasMsgId();
    com.wangboo.cluster.protocol.MsgIdProto.MsgId getMsgId();
    
    // optional int32 result = 2;
    boolean hasResult();
    int getResult();
    
    // optional .G2C_LoginResp loginResp = 10;
    boolean hasLoginResp();
    com.wangboo.cluster.protocol.Gate2ClientProto.G2C_LoginResp getLoginResp();
    com.wangboo.cluster.protocol.Gate2ClientProto.G2C_LoginRespOrBuilder getLoginRespOrBuilder();
    
    // optional .G2C_Talk talk = 11;
    boolean hasTalk();
    com.wangboo.cluster.protocol.Gate2ClientProto.G2C_Talk getTalk();
    com.wangboo.cluster.protocol.Gate2ClientProto.G2C_TalkOrBuilder getTalkOrBuilder();
  }
  public static final class Gate2ClientMsg extends
      com.google.protobuf.GeneratedMessage
      implements Gate2ClientMsgOrBuilder {
    // Use Gate2ClientMsg.newBuilder() to construct.
    private Gate2ClientMsg(Builder builder) {
      super(builder);
    }
    private Gate2ClientMsg(boolean noInit) {}
    
    private static final Gate2ClientMsg defaultInstance;
    public static Gate2ClientMsg getDefaultInstance() {
      return defaultInstance;
    }
    
    public Gate2ClientMsg getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.wangboo.cluster.protocol.Gate2ClientProto.internal_static_Gate2ClientMsg_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.wangboo.cluster.protocol.Gate2ClientProto.internal_static_Gate2ClientMsg_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required .MsgId msgId = 1;
    public static final int MSGID_FIELD_NUMBER = 1;
    private com.wangboo.cluster.protocol.MsgIdProto.MsgId msgId_;
    public boolean hasMsgId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public com.wangboo.cluster.protocol.MsgIdProto.MsgId getMsgId() {
      return msgId_;
    }
    
    // optional int32 result = 2;
    public static final int RESULT_FIELD_NUMBER = 2;
    private int result_;
    public boolean hasResult() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getResult() {
      return result_;
    }
    
    // optional .G2C_LoginResp loginResp = 10;
    public static final int LOGINRESP_FIELD_NUMBER = 10;
    private com.wangboo.cluster.protocol.Gate2ClientProto.G2C_LoginResp loginResp_;
    public boolean hasLoginResp() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public com.wangboo.cluster.protocol.Gate2ClientProto.G2C_LoginResp getLoginResp() {
      return loginResp_;
    }
    public com.wangboo.cluster.protocol.Gate2ClientProto.G2C_LoginRespOrBuilder getLoginRespOrBuilder() {
      return loginResp_;
    }
    
    // optional .G2C_Talk talk = 11;
    public static final int TALK_FIELD_NUMBER = 11;
    private com.wangboo.cluster.protocol.Gate2ClientProto.G2C_Talk talk_;
    public boolean hasTalk() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public com.wangboo.cluster.protocol.Gate2ClientProto.G2C_Talk getTalk() {
      return talk_;
    }
    public com.wangboo.cluster.protocol.Gate2ClientProto.G2C_TalkOrBuilder getTalkOrBuilder() {
      return talk_;
    }
    
    private void initFields() {
      msgId_ = com.wangboo.cluster.protocol.MsgIdProto.MsgId.Common_HeartBeat;
      result_ = 0;
      loginResp_ = com.wangboo.cluster.protocol.Gate2ClientProto.G2C_LoginResp.getDefaultInstance();
      talk_ = com.wangboo.cluster.protocol.Gate2ClientProto.G2C_Talk.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasMsgId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasLoginResp()) {
        if (!getLoginResp().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasTalk()) {
        if (!getTalk().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, msgId_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, result_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(10, loginResp_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeMessage(11, talk_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, msgId_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, result_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(10, loginResp_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(11, talk_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.wangboo.cluster.protocol.Gate2ClientProto.Gate2ClientMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.wangboo.cluster.protocol.Gate2ClientProto.Gate2ClientMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.wangboo.cluster.protocol.Gate2ClientProto.Gate2ClientMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.wangboo.cluster.protocol.Gate2ClientProto.Gate2ClientMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.wangboo.cluster.protocol.Gate2ClientProto.Gate2ClientMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.wangboo.cluster.protocol.Gate2ClientProto.Gate2ClientMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.wangboo.cluster.protocol.Gate2ClientProto.Gate2ClientMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.wangboo.cluster.protocol.Gate2ClientProto.Gate2ClientMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.wangboo.cluster.protocol.Gate2ClientProto.Gate2ClientMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.wangboo.cluster.protocol.Gate2ClientProto.Gate2ClientMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.wangboo.cluster.protocol.Gate2ClientProto.Gate2ClientMsg prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.wangboo.cluster.protocol.Gate2ClientProto.Gate2ClientMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.wangboo.cluster.protocol.Gate2ClientProto.internal_static_Gate2ClientMsg_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.wangboo.cluster.protocol.Gate2ClientProto.internal_static_Gate2ClientMsg_fieldAccessorTable;
      }
      
      // Construct using com.wangboo.cluster.protocol.Gate2ClientProto.Gate2ClientMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getLoginRespFieldBuilder();
          getTalkFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        msgId_ = com.wangboo.cluster.protocol.MsgIdProto.MsgId.Common_HeartBeat;
        bitField0_ = (bitField0_ & ~0x00000001);
        result_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        if (loginRespBuilder_ == null) {
          loginResp_ = com.wangboo.cluster.protocol.Gate2ClientProto.G2C_LoginResp.getDefaultInstance();
        } else {
          loginRespBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        if (talkBuilder_ == null) {
          talk_ = com.wangboo.cluster.protocol.Gate2ClientProto.G2C_Talk.getDefaultInstance();
        } else {
          talkBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.wangboo.cluster.protocol.Gate2ClientProto.Gate2ClientMsg.getDescriptor();
      }
      
      public com.wangboo.cluster.protocol.Gate2ClientProto.Gate2ClientMsg getDefaultInstanceForType() {
        return com.wangboo.cluster.protocol.Gate2ClientProto.Gate2ClientMsg.getDefaultInstance();
      }
      
      public com.wangboo.cluster.protocol.Gate2ClientProto.Gate2ClientMsg build() {
        com.wangboo.cluster.protocol.Gate2ClientProto.Gate2ClientMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.wangboo.cluster.protocol.Gate2ClientProto.Gate2ClientMsg buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.wangboo.cluster.protocol.Gate2ClientProto.Gate2ClientMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.wangboo.cluster.protocol.Gate2ClientProto.Gate2ClientMsg buildPartial() {
        com.wangboo.cluster.protocol.Gate2ClientProto.Gate2ClientMsg result = new com.wangboo.cluster.protocol.Gate2ClientProto.Gate2ClientMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.msgId_ = msgId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.result_ = result_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (loginRespBuilder_ == null) {
          result.loginResp_ = loginResp_;
        } else {
          result.loginResp_ = loginRespBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        if (talkBuilder_ == null) {
          result.talk_ = talk_;
        } else {
          result.talk_ = talkBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.wangboo.cluster.protocol.Gate2ClientProto.Gate2ClientMsg) {
          return mergeFrom((com.wangboo.cluster.protocol.Gate2ClientProto.Gate2ClientMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.wangboo.cluster.protocol.Gate2ClientProto.Gate2ClientMsg other) {
        if (other == com.wangboo.cluster.protocol.Gate2ClientProto.Gate2ClientMsg.getDefaultInstance()) return this;
        if (other.hasMsgId()) {
          setMsgId(other.getMsgId());
        }
        if (other.hasResult()) {
          setResult(other.getResult());
        }
        if (other.hasLoginResp()) {
          mergeLoginResp(other.getLoginResp());
        }
        if (other.hasTalk()) {
          mergeTalk(other.getTalk());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasMsgId()) {
          
          return false;
        }
        if (hasLoginResp()) {
          if (!getLoginResp().isInitialized()) {
            
            return false;
          }
        }
        if (hasTalk()) {
          if (!getTalk().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.wangboo.cluster.protocol.MsgIdProto.MsgId value = com.wangboo.cluster.protocol.MsgIdProto.MsgId.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                msgId_ = value;
              }
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              result_ = input.readInt32();
              break;
            }
            case 82: {
              com.wangboo.cluster.protocol.Gate2ClientProto.G2C_LoginResp.Builder subBuilder = com.wangboo.cluster.protocol.Gate2ClientProto.G2C_LoginResp.newBuilder();
              if (hasLoginResp()) {
                subBuilder.mergeFrom(getLoginResp());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setLoginResp(subBuilder.buildPartial());
              break;
            }
            case 90: {
              com.wangboo.cluster.protocol.Gate2ClientProto.G2C_Talk.Builder subBuilder = com.wangboo.cluster.protocol.Gate2ClientProto.G2C_Talk.newBuilder();
              if (hasTalk()) {
                subBuilder.mergeFrom(getTalk());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setTalk(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required .MsgId msgId = 1;
      private com.wangboo.cluster.protocol.MsgIdProto.MsgId msgId_ = com.wangboo.cluster.protocol.MsgIdProto.MsgId.Common_HeartBeat;
      public boolean hasMsgId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public com.wangboo.cluster.protocol.MsgIdProto.MsgId getMsgId() {
        return msgId_;
      }
      public Builder setMsgId(com.wangboo.cluster.protocol.MsgIdProto.MsgId value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        msgId_ = value;
        onChanged();
        return this;
      }
      public Builder clearMsgId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        msgId_ = com.wangboo.cluster.protocol.MsgIdProto.MsgId.Common_HeartBeat;
        onChanged();
        return this;
      }
      
      // optional int32 result = 2;
      private int result_ ;
      public boolean hasResult() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getResult() {
        return result_;
      }
      public Builder setResult(int value) {
        bitField0_ |= 0x00000002;
        result_ = value;
        onChanged();
        return this;
      }
      public Builder clearResult() {
        bitField0_ = (bitField0_ & ~0x00000002);
        result_ = 0;
        onChanged();
        return this;
      }
      
      // optional .G2C_LoginResp loginResp = 10;
      private com.wangboo.cluster.protocol.Gate2ClientProto.G2C_LoginResp loginResp_ = com.wangboo.cluster.protocol.Gate2ClientProto.G2C_LoginResp.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.wangboo.cluster.protocol.Gate2ClientProto.G2C_LoginResp, com.wangboo.cluster.protocol.Gate2ClientProto.G2C_LoginResp.Builder, com.wangboo.cluster.protocol.Gate2ClientProto.G2C_LoginRespOrBuilder> loginRespBuilder_;
      public boolean hasLoginResp() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public com.wangboo.cluster.protocol.Gate2ClientProto.G2C_LoginResp getLoginResp() {
        if (loginRespBuilder_ == null) {
          return loginResp_;
        } else {
          return loginRespBuilder_.getMessage();
        }
      }
      public Builder setLoginResp(com.wangboo.cluster.protocol.Gate2ClientProto.G2C_LoginResp value) {
        if (loginRespBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          loginResp_ = value;
          onChanged();
        } else {
          loginRespBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      public Builder setLoginResp(
          com.wangboo.cluster.protocol.Gate2ClientProto.G2C_LoginResp.Builder builderForValue) {
        if (loginRespBuilder_ == null) {
          loginResp_ = builderForValue.build();
          onChanged();
        } else {
          loginRespBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      public Builder mergeLoginResp(com.wangboo.cluster.protocol.Gate2ClientProto.G2C_LoginResp value) {
        if (loginRespBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              loginResp_ != com.wangboo.cluster.protocol.Gate2ClientProto.G2C_LoginResp.getDefaultInstance()) {
            loginResp_ =
              com.wangboo.cluster.protocol.Gate2ClientProto.G2C_LoginResp.newBuilder(loginResp_).mergeFrom(value).buildPartial();
          } else {
            loginResp_ = value;
          }
          onChanged();
        } else {
          loginRespBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      public Builder clearLoginResp() {
        if (loginRespBuilder_ == null) {
          loginResp_ = com.wangboo.cluster.protocol.Gate2ClientProto.G2C_LoginResp.getDefaultInstance();
          onChanged();
        } else {
          loginRespBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      public com.wangboo.cluster.protocol.Gate2ClientProto.G2C_LoginResp.Builder getLoginRespBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getLoginRespFieldBuilder().getBuilder();
      }
      public com.wangboo.cluster.protocol.Gate2ClientProto.G2C_LoginRespOrBuilder getLoginRespOrBuilder() {
        if (loginRespBuilder_ != null) {
          return loginRespBuilder_.getMessageOrBuilder();
        } else {
          return loginResp_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          com.wangboo.cluster.protocol.Gate2ClientProto.G2C_LoginResp, com.wangboo.cluster.protocol.Gate2ClientProto.G2C_LoginResp.Builder, com.wangboo.cluster.protocol.Gate2ClientProto.G2C_LoginRespOrBuilder> 
          getLoginRespFieldBuilder() {
        if (loginRespBuilder_ == null) {
          loginRespBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.wangboo.cluster.protocol.Gate2ClientProto.G2C_LoginResp, com.wangboo.cluster.protocol.Gate2ClientProto.G2C_LoginResp.Builder, com.wangboo.cluster.protocol.Gate2ClientProto.G2C_LoginRespOrBuilder>(
                  loginResp_,
                  getParentForChildren(),
                  isClean());
          loginResp_ = null;
        }
        return loginRespBuilder_;
      }
      
      // optional .G2C_Talk talk = 11;
      private com.wangboo.cluster.protocol.Gate2ClientProto.G2C_Talk talk_ = com.wangboo.cluster.protocol.Gate2ClientProto.G2C_Talk.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.wangboo.cluster.protocol.Gate2ClientProto.G2C_Talk, com.wangboo.cluster.protocol.Gate2ClientProto.G2C_Talk.Builder, com.wangboo.cluster.protocol.Gate2ClientProto.G2C_TalkOrBuilder> talkBuilder_;
      public boolean hasTalk() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public com.wangboo.cluster.protocol.Gate2ClientProto.G2C_Talk getTalk() {
        if (talkBuilder_ == null) {
          return talk_;
        } else {
          return talkBuilder_.getMessage();
        }
      }
      public Builder setTalk(com.wangboo.cluster.protocol.Gate2ClientProto.G2C_Talk value) {
        if (talkBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          talk_ = value;
          onChanged();
        } else {
          talkBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      public Builder setTalk(
          com.wangboo.cluster.protocol.Gate2ClientProto.G2C_Talk.Builder builderForValue) {
        if (talkBuilder_ == null) {
          talk_ = builderForValue.build();
          onChanged();
        } else {
          talkBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      public Builder mergeTalk(com.wangboo.cluster.protocol.Gate2ClientProto.G2C_Talk value) {
        if (talkBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008) &&
              talk_ != com.wangboo.cluster.protocol.Gate2ClientProto.G2C_Talk.getDefaultInstance()) {
            talk_ =
              com.wangboo.cluster.protocol.Gate2ClientProto.G2C_Talk.newBuilder(talk_).mergeFrom(value).buildPartial();
          } else {
            talk_ = value;
          }
          onChanged();
        } else {
          talkBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      public Builder clearTalk() {
        if (talkBuilder_ == null) {
          talk_ = com.wangboo.cluster.protocol.Gate2ClientProto.G2C_Talk.getDefaultInstance();
          onChanged();
        } else {
          talkBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      public com.wangboo.cluster.protocol.Gate2ClientProto.G2C_Talk.Builder getTalkBuilder() {
        bitField0_ |= 0x00000008;
        onChanged();
        return getTalkFieldBuilder().getBuilder();
      }
      public com.wangboo.cluster.protocol.Gate2ClientProto.G2C_TalkOrBuilder getTalkOrBuilder() {
        if (talkBuilder_ != null) {
          return talkBuilder_.getMessageOrBuilder();
        } else {
          return talk_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          com.wangboo.cluster.protocol.Gate2ClientProto.G2C_Talk, com.wangboo.cluster.protocol.Gate2ClientProto.G2C_Talk.Builder, com.wangboo.cluster.protocol.Gate2ClientProto.G2C_TalkOrBuilder> 
          getTalkFieldBuilder() {
        if (talkBuilder_ == null) {
          talkBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.wangboo.cluster.protocol.Gate2ClientProto.G2C_Talk, com.wangboo.cluster.protocol.Gate2ClientProto.G2C_Talk.Builder, com.wangboo.cluster.protocol.Gate2ClientProto.G2C_TalkOrBuilder>(
                  talk_,
                  getParentForChildren(),
                  isClean());
          talk_ = null;
        }
        return talkBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:Gate2ClientMsg)
    }
    
    static {
      defaultInstance = new Gate2ClientMsg(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:Gate2ClientMsg)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_G2C_LoginResp_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_G2C_LoginResp_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_G2C_Talk_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_G2C_Talk_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Gate2ClientMsg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Gate2ClientMsg_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021gate2client.proto\032\013msgid.proto\"\036\n\rG2C_" +
      "LoginResp\022\r\n\005token\030\001 \002(\t\"9\n\010G2C_Talk\022\013\n\003" +
      "msg\030\001 \002(\t\022\016\n\006fromId\030\002 \002(\003\022\020\n\010fromName\030\003 " +
      "\002(\t\"s\n\016Gate2ClientMsg\022\025\n\005msgId\030\001 \002(\0162\006.M" +
      "sgId\022\016\n\006result\030\002 \001(\005\022!\n\tloginResp\030\n \001(\0132" +
      "\016.G2C_LoginResp\022\027\n\004talk\030\013 \001(\0132\t.G2C_Talk" +
      "B0\n\034com.wangboo.cluster.protocolB\020Gate2C" +
      "lientProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_G2C_LoginResp_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_G2C_LoginResp_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_G2C_LoginResp_descriptor,
              new java.lang.String[] { "Token", },
              com.wangboo.cluster.protocol.Gate2ClientProto.G2C_LoginResp.class,
              com.wangboo.cluster.protocol.Gate2ClientProto.G2C_LoginResp.Builder.class);
          internal_static_G2C_Talk_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_G2C_Talk_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_G2C_Talk_descriptor,
              new java.lang.String[] { "Msg", "FromId", "FromName", },
              com.wangboo.cluster.protocol.Gate2ClientProto.G2C_Talk.class,
              com.wangboo.cluster.protocol.Gate2ClientProto.G2C_Talk.Builder.class);
          internal_static_Gate2ClientMsg_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_Gate2ClientMsg_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Gate2ClientMsg_descriptor,
              new java.lang.String[] { "MsgId", "Result", "LoginResp", "Talk", },
              com.wangboo.cluster.protocol.Gate2ClientProto.Gate2ClientMsg.class,
              com.wangboo.cluster.protocol.Gate2ClientProto.Gate2ClientMsg.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.wangboo.cluster.protocol.MsgIdProto.getDescriptor(),
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
