// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: login2client.proto

package com.wangboo.cluster.protocol;

public final class L2cProto {
  private L2cProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface C2LMessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required .MsgId msgId = 1;
    boolean hasMsgId();
    com.wangboo.cluster.protocol.MsgIdProto.MsgId getMsgId();
  }
  public static final class C2LMessage extends
      com.google.protobuf.GeneratedMessage
      implements C2LMessageOrBuilder {
    // Use C2LMessage.newBuilder() to construct.
    private C2LMessage(Builder builder) {
      super(builder);
    }
    private C2LMessage(boolean noInit) {}
    
    private static final C2LMessage defaultInstance;
    public static C2LMessage getDefaultInstance() {
      return defaultInstance;
    }
    
    public C2LMessage getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.wangboo.cluster.protocol.L2cProto.internal_static_C2LMessage_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.wangboo.cluster.protocol.L2cProto.internal_static_C2LMessage_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required .MsgId msgId = 1;
    public static final int MSGID_FIELD_NUMBER = 1;
    private com.wangboo.cluster.protocol.MsgIdProto.MsgId msgId_;
    public boolean hasMsgId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public com.wangboo.cluster.protocol.MsgIdProto.MsgId getMsgId() {
      return msgId_;
    }
    
    private void initFields() {
      msgId_ = com.wangboo.cluster.protocol.MsgIdProto.MsgId.Common_HeartBeat;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasMsgId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, msgId_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, msgId_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.wangboo.cluster.protocol.L2cProto.C2LMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.wangboo.cluster.protocol.L2cProto.C2LMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.wangboo.cluster.protocol.L2cProto.C2LMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.wangboo.cluster.protocol.L2cProto.C2LMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.wangboo.cluster.protocol.L2cProto.C2LMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.wangboo.cluster.protocol.L2cProto.C2LMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.wangboo.cluster.protocol.L2cProto.C2LMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.wangboo.cluster.protocol.L2cProto.C2LMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.wangboo.cluster.protocol.L2cProto.C2LMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.wangboo.cluster.protocol.L2cProto.C2LMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.wangboo.cluster.protocol.L2cProto.C2LMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.wangboo.cluster.protocol.L2cProto.C2LMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.wangboo.cluster.protocol.L2cProto.internal_static_C2LMessage_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.wangboo.cluster.protocol.L2cProto.internal_static_C2LMessage_fieldAccessorTable;
      }
      
      // Construct using com.wangboo.cluster.protocol.L2cProto.C2LMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        msgId_ = com.wangboo.cluster.protocol.MsgIdProto.MsgId.Common_HeartBeat;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.wangboo.cluster.protocol.L2cProto.C2LMessage.getDescriptor();
      }
      
      public com.wangboo.cluster.protocol.L2cProto.C2LMessage getDefaultInstanceForType() {
        return com.wangboo.cluster.protocol.L2cProto.C2LMessage.getDefaultInstance();
      }
      
      public com.wangboo.cluster.protocol.L2cProto.C2LMessage build() {
        com.wangboo.cluster.protocol.L2cProto.C2LMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.wangboo.cluster.protocol.L2cProto.C2LMessage buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.wangboo.cluster.protocol.L2cProto.C2LMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.wangboo.cluster.protocol.L2cProto.C2LMessage buildPartial() {
        com.wangboo.cluster.protocol.L2cProto.C2LMessage result = new com.wangboo.cluster.protocol.L2cProto.C2LMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.msgId_ = msgId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.wangboo.cluster.protocol.L2cProto.C2LMessage) {
          return mergeFrom((com.wangboo.cluster.protocol.L2cProto.C2LMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.wangboo.cluster.protocol.L2cProto.C2LMessage other) {
        if (other == com.wangboo.cluster.protocol.L2cProto.C2LMessage.getDefaultInstance()) return this;
        if (other.hasMsgId()) {
          setMsgId(other.getMsgId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasMsgId()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.wangboo.cluster.protocol.MsgIdProto.MsgId value = com.wangboo.cluster.protocol.MsgIdProto.MsgId.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                msgId_ = value;
              }
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required .MsgId msgId = 1;
      private com.wangboo.cluster.protocol.MsgIdProto.MsgId msgId_ = com.wangboo.cluster.protocol.MsgIdProto.MsgId.Common_HeartBeat;
      public boolean hasMsgId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public com.wangboo.cluster.protocol.MsgIdProto.MsgId getMsgId() {
        return msgId_;
      }
      public Builder setMsgId(com.wangboo.cluster.protocol.MsgIdProto.MsgId value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        msgId_ = value;
        onChanged();
        return this;
      }
      public Builder clearMsgId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        msgId_ = com.wangboo.cluster.protocol.MsgIdProto.MsgId.Common_HeartBeat;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:C2LMessage)
    }
    
    static {
      defaultInstance = new C2LMessage(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:C2LMessage)
  }
  
  public interface L2CProxyInfoRespOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int32 state = 1;
    boolean hasState();
    int getState();
    
    // optional string ip = 2;
    boolean hasIp();
    String getIp();
    
    // optional int32 port = 3;
    boolean hasPort();
    int getPort();
    
    // optional int32 count = 4;
    boolean hasCount();
    int getCount();
  }
  public static final class L2CProxyInfoResp extends
      com.google.protobuf.GeneratedMessage
      implements L2CProxyInfoRespOrBuilder {
    // Use L2CProxyInfoResp.newBuilder() to construct.
    private L2CProxyInfoResp(Builder builder) {
      super(builder);
    }
    private L2CProxyInfoResp(boolean noInit) {}
    
    private static final L2CProxyInfoResp defaultInstance;
    public static L2CProxyInfoResp getDefaultInstance() {
      return defaultInstance;
    }
    
    public L2CProxyInfoResp getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.wangboo.cluster.protocol.L2cProto.internal_static_L2CProxyInfoResp_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.wangboo.cluster.protocol.L2cProto.internal_static_L2CProxyInfoResp_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int32 state = 1;
    public static final int STATE_FIELD_NUMBER = 1;
    private int state_;
    public boolean hasState() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getState() {
      return state_;
    }
    
    // optional string ip = 2;
    public static final int IP_FIELD_NUMBER = 2;
    private java.lang.Object ip_;
    public boolean hasIp() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getIp() {
      java.lang.Object ref = ip_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          ip_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getIpBytes() {
      java.lang.Object ref = ip_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        ip_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional int32 port = 3;
    public static final int PORT_FIELD_NUMBER = 3;
    private int port_;
    public boolean hasPort() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public int getPort() {
      return port_;
    }
    
    // optional int32 count = 4;
    public static final int COUNT_FIELD_NUMBER = 4;
    private int count_;
    public boolean hasCount() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public int getCount() {
      return count_;
    }
    
    private void initFields() {
      state_ = 0;
      ip_ = "";
      port_ = 0;
      count_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasState()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, state_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getIpBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, port_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, count_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, state_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getIpBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, port_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, count_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.wangboo.cluster.protocol.L2cProto.L2CProxyInfoResp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.wangboo.cluster.protocol.L2cProto.L2CProxyInfoResp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.wangboo.cluster.protocol.L2cProto.L2CProxyInfoResp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.wangboo.cluster.protocol.L2cProto.L2CProxyInfoResp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.wangboo.cluster.protocol.L2cProto.L2CProxyInfoResp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.wangboo.cluster.protocol.L2cProto.L2CProxyInfoResp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.wangboo.cluster.protocol.L2cProto.L2CProxyInfoResp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.wangboo.cluster.protocol.L2cProto.L2CProxyInfoResp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.wangboo.cluster.protocol.L2cProto.L2CProxyInfoResp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.wangboo.cluster.protocol.L2cProto.L2CProxyInfoResp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.wangboo.cluster.protocol.L2cProto.L2CProxyInfoResp prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.wangboo.cluster.protocol.L2cProto.L2CProxyInfoRespOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.wangboo.cluster.protocol.L2cProto.internal_static_L2CProxyInfoResp_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.wangboo.cluster.protocol.L2cProto.internal_static_L2CProxyInfoResp_fieldAccessorTable;
      }
      
      // Construct using com.wangboo.cluster.protocol.L2cProto.L2CProxyInfoResp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        state_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        ip_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        port_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        count_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.wangboo.cluster.protocol.L2cProto.L2CProxyInfoResp.getDescriptor();
      }
      
      public com.wangboo.cluster.protocol.L2cProto.L2CProxyInfoResp getDefaultInstanceForType() {
        return com.wangboo.cluster.protocol.L2cProto.L2CProxyInfoResp.getDefaultInstance();
      }
      
      public com.wangboo.cluster.protocol.L2cProto.L2CProxyInfoResp build() {
        com.wangboo.cluster.protocol.L2cProto.L2CProxyInfoResp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.wangboo.cluster.protocol.L2cProto.L2CProxyInfoResp buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.wangboo.cluster.protocol.L2cProto.L2CProxyInfoResp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.wangboo.cluster.protocol.L2cProto.L2CProxyInfoResp buildPartial() {
        com.wangboo.cluster.protocol.L2cProto.L2CProxyInfoResp result = new com.wangboo.cluster.protocol.L2cProto.L2CProxyInfoResp(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.state_ = state_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.ip_ = ip_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.port_ = port_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.count_ = count_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.wangboo.cluster.protocol.L2cProto.L2CProxyInfoResp) {
          return mergeFrom((com.wangboo.cluster.protocol.L2cProto.L2CProxyInfoResp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.wangboo.cluster.protocol.L2cProto.L2CProxyInfoResp other) {
        if (other == com.wangboo.cluster.protocol.L2cProto.L2CProxyInfoResp.getDefaultInstance()) return this;
        if (other.hasState()) {
          setState(other.getState());
        }
        if (other.hasIp()) {
          setIp(other.getIp());
        }
        if (other.hasPort()) {
          setPort(other.getPort());
        }
        if (other.hasCount()) {
          setCount(other.getCount());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasState()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              state_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              ip_ = input.readBytes();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              port_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              count_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 state = 1;
      private int state_ ;
      public boolean hasState() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getState() {
        return state_;
      }
      public Builder setState(int value) {
        bitField0_ |= 0x00000001;
        state_ = value;
        onChanged();
        return this;
      }
      public Builder clearState() {
        bitField0_ = (bitField0_ & ~0x00000001);
        state_ = 0;
        onChanged();
        return this;
      }
      
      // optional string ip = 2;
      private java.lang.Object ip_ = "";
      public boolean hasIp() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getIp() {
        java.lang.Object ref = ip_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          ip_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setIp(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        ip_ = value;
        onChanged();
        return this;
      }
      public Builder clearIp() {
        bitField0_ = (bitField0_ & ~0x00000002);
        ip_ = getDefaultInstance().getIp();
        onChanged();
        return this;
      }
      void setIp(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        ip_ = value;
        onChanged();
      }
      
      // optional int32 port = 3;
      private int port_ ;
      public boolean hasPort() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getPort() {
        return port_;
      }
      public Builder setPort(int value) {
        bitField0_ |= 0x00000004;
        port_ = value;
        onChanged();
        return this;
      }
      public Builder clearPort() {
        bitField0_ = (bitField0_ & ~0x00000004);
        port_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 count = 4;
      private int count_ ;
      public boolean hasCount() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public int getCount() {
        return count_;
      }
      public Builder setCount(int value) {
        bitField0_ |= 0x00000008;
        count_ = value;
        onChanged();
        return this;
      }
      public Builder clearCount() {
        bitField0_ = (bitField0_ & ~0x00000008);
        count_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:L2CProxyInfoResp)
    }
    
    static {
      defaultInstance = new L2CProxyInfoResp(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:L2CProxyInfoResp)
  }
  
  public interface L2CMessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required .MsgId msgId = 1;
    boolean hasMsgId();
    com.wangboo.cluster.protocol.MsgIdProto.MsgId getMsgId();
    
    // optional .L2CProxyInfoResp proxyInfoResp = 2;
    boolean hasProxyInfoResp();
    com.wangboo.cluster.protocol.L2cProto.L2CProxyInfoResp getProxyInfoResp();
    com.wangboo.cluster.protocol.L2cProto.L2CProxyInfoRespOrBuilder getProxyInfoRespOrBuilder();
  }
  public static final class L2CMessage extends
      com.google.protobuf.GeneratedMessage
      implements L2CMessageOrBuilder {
    // Use L2CMessage.newBuilder() to construct.
    private L2CMessage(Builder builder) {
      super(builder);
    }
    private L2CMessage(boolean noInit) {}
    
    private static final L2CMessage defaultInstance;
    public static L2CMessage getDefaultInstance() {
      return defaultInstance;
    }
    
    public L2CMessage getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.wangboo.cluster.protocol.L2cProto.internal_static_L2CMessage_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.wangboo.cluster.protocol.L2cProto.internal_static_L2CMessage_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required .MsgId msgId = 1;
    public static final int MSGID_FIELD_NUMBER = 1;
    private com.wangboo.cluster.protocol.MsgIdProto.MsgId msgId_;
    public boolean hasMsgId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public com.wangboo.cluster.protocol.MsgIdProto.MsgId getMsgId() {
      return msgId_;
    }
    
    // optional .L2CProxyInfoResp proxyInfoResp = 2;
    public static final int PROXYINFORESP_FIELD_NUMBER = 2;
    private com.wangboo.cluster.protocol.L2cProto.L2CProxyInfoResp proxyInfoResp_;
    public boolean hasProxyInfoResp() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public com.wangboo.cluster.protocol.L2cProto.L2CProxyInfoResp getProxyInfoResp() {
      return proxyInfoResp_;
    }
    public com.wangboo.cluster.protocol.L2cProto.L2CProxyInfoRespOrBuilder getProxyInfoRespOrBuilder() {
      return proxyInfoResp_;
    }
    
    private void initFields() {
      msgId_ = com.wangboo.cluster.protocol.MsgIdProto.MsgId.Common_HeartBeat;
      proxyInfoResp_ = com.wangboo.cluster.protocol.L2cProto.L2CProxyInfoResp.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasMsgId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasProxyInfoResp()) {
        if (!getProxyInfoResp().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, msgId_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, proxyInfoResp_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, msgId_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, proxyInfoResp_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.wangboo.cluster.protocol.L2cProto.L2CMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.wangboo.cluster.protocol.L2cProto.L2CMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.wangboo.cluster.protocol.L2cProto.L2CMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.wangboo.cluster.protocol.L2cProto.L2CMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.wangboo.cluster.protocol.L2cProto.L2CMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.wangboo.cluster.protocol.L2cProto.L2CMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.wangboo.cluster.protocol.L2cProto.L2CMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.wangboo.cluster.protocol.L2cProto.L2CMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.wangboo.cluster.protocol.L2cProto.L2CMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.wangboo.cluster.protocol.L2cProto.L2CMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.wangboo.cluster.protocol.L2cProto.L2CMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.wangboo.cluster.protocol.L2cProto.L2CMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.wangboo.cluster.protocol.L2cProto.internal_static_L2CMessage_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.wangboo.cluster.protocol.L2cProto.internal_static_L2CMessage_fieldAccessorTable;
      }
      
      // Construct using com.wangboo.cluster.protocol.L2cProto.L2CMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getProxyInfoRespFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        msgId_ = com.wangboo.cluster.protocol.MsgIdProto.MsgId.Common_HeartBeat;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (proxyInfoRespBuilder_ == null) {
          proxyInfoResp_ = com.wangboo.cluster.protocol.L2cProto.L2CProxyInfoResp.getDefaultInstance();
        } else {
          proxyInfoRespBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.wangboo.cluster.protocol.L2cProto.L2CMessage.getDescriptor();
      }
      
      public com.wangboo.cluster.protocol.L2cProto.L2CMessage getDefaultInstanceForType() {
        return com.wangboo.cluster.protocol.L2cProto.L2CMessage.getDefaultInstance();
      }
      
      public com.wangboo.cluster.protocol.L2cProto.L2CMessage build() {
        com.wangboo.cluster.protocol.L2cProto.L2CMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.wangboo.cluster.protocol.L2cProto.L2CMessage buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.wangboo.cluster.protocol.L2cProto.L2CMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.wangboo.cluster.protocol.L2cProto.L2CMessage buildPartial() {
        com.wangboo.cluster.protocol.L2cProto.L2CMessage result = new com.wangboo.cluster.protocol.L2cProto.L2CMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.msgId_ = msgId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (proxyInfoRespBuilder_ == null) {
          result.proxyInfoResp_ = proxyInfoResp_;
        } else {
          result.proxyInfoResp_ = proxyInfoRespBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.wangboo.cluster.protocol.L2cProto.L2CMessage) {
          return mergeFrom((com.wangboo.cluster.protocol.L2cProto.L2CMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.wangboo.cluster.protocol.L2cProto.L2CMessage other) {
        if (other == com.wangboo.cluster.protocol.L2cProto.L2CMessage.getDefaultInstance()) return this;
        if (other.hasMsgId()) {
          setMsgId(other.getMsgId());
        }
        if (other.hasProxyInfoResp()) {
          mergeProxyInfoResp(other.getProxyInfoResp());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasMsgId()) {
          
          return false;
        }
        if (hasProxyInfoResp()) {
          if (!getProxyInfoResp().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.wangboo.cluster.protocol.MsgIdProto.MsgId value = com.wangboo.cluster.protocol.MsgIdProto.MsgId.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                msgId_ = value;
              }
              break;
            }
            case 18: {
              com.wangboo.cluster.protocol.L2cProto.L2CProxyInfoResp.Builder subBuilder = com.wangboo.cluster.protocol.L2cProto.L2CProxyInfoResp.newBuilder();
              if (hasProxyInfoResp()) {
                subBuilder.mergeFrom(getProxyInfoResp());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setProxyInfoResp(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required .MsgId msgId = 1;
      private com.wangboo.cluster.protocol.MsgIdProto.MsgId msgId_ = com.wangboo.cluster.protocol.MsgIdProto.MsgId.Common_HeartBeat;
      public boolean hasMsgId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public com.wangboo.cluster.protocol.MsgIdProto.MsgId getMsgId() {
        return msgId_;
      }
      public Builder setMsgId(com.wangboo.cluster.protocol.MsgIdProto.MsgId value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        msgId_ = value;
        onChanged();
        return this;
      }
      public Builder clearMsgId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        msgId_ = com.wangboo.cluster.protocol.MsgIdProto.MsgId.Common_HeartBeat;
        onChanged();
        return this;
      }
      
      // optional .L2CProxyInfoResp proxyInfoResp = 2;
      private com.wangboo.cluster.protocol.L2cProto.L2CProxyInfoResp proxyInfoResp_ = com.wangboo.cluster.protocol.L2cProto.L2CProxyInfoResp.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.wangboo.cluster.protocol.L2cProto.L2CProxyInfoResp, com.wangboo.cluster.protocol.L2cProto.L2CProxyInfoResp.Builder, com.wangboo.cluster.protocol.L2cProto.L2CProxyInfoRespOrBuilder> proxyInfoRespBuilder_;
      public boolean hasProxyInfoResp() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public com.wangboo.cluster.protocol.L2cProto.L2CProxyInfoResp getProxyInfoResp() {
        if (proxyInfoRespBuilder_ == null) {
          return proxyInfoResp_;
        } else {
          return proxyInfoRespBuilder_.getMessage();
        }
      }
      public Builder setProxyInfoResp(com.wangboo.cluster.protocol.L2cProto.L2CProxyInfoResp value) {
        if (proxyInfoRespBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          proxyInfoResp_ = value;
          onChanged();
        } else {
          proxyInfoRespBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder setProxyInfoResp(
          com.wangboo.cluster.protocol.L2cProto.L2CProxyInfoResp.Builder builderForValue) {
        if (proxyInfoRespBuilder_ == null) {
          proxyInfoResp_ = builderForValue.build();
          onChanged();
        } else {
          proxyInfoRespBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder mergeProxyInfoResp(com.wangboo.cluster.protocol.L2cProto.L2CProxyInfoResp value) {
        if (proxyInfoRespBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              proxyInfoResp_ != com.wangboo.cluster.protocol.L2cProto.L2CProxyInfoResp.getDefaultInstance()) {
            proxyInfoResp_ =
              com.wangboo.cluster.protocol.L2cProto.L2CProxyInfoResp.newBuilder(proxyInfoResp_).mergeFrom(value).buildPartial();
          } else {
            proxyInfoResp_ = value;
          }
          onChanged();
        } else {
          proxyInfoRespBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder clearProxyInfoResp() {
        if (proxyInfoRespBuilder_ == null) {
          proxyInfoResp_ = com.wangboo.cluster.protocol.L2cProto.L2CProxyInfoResp.getDefaultInstance();
          onChanged();
        } else {
          proxyInfoRespBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      public com.wangboo.cluster.protocol.L2cProto.L2CProxyInfoResp.Builder getProxyInfoRespBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getProxyInfoRespFieldBuilder().getBuilder();
      }
      public com.wangboo.cluster.protocol.L2cProto.L2CProxyInfoRespOrBuilder getProxyInfoRespOrBuilder() {
        if (proxyInfoRespBuilder_ != null) {
          return proxyInfoRespBuilder_.getMessageOrBuilder();
        } else {
          return proxyInfoResp_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          com.wangboo.cluster.protocol.L2cProto.L2CProxyInfoResp, com.wangboo.cluster.protocol.L2cProto.L2CProxyInfoResp.Builder, com.wangboo.cluster.protocol.L2cProto.L2CProxyInfoRespOrBuilder> 
          getProxyInfoRespFieldBuilder() {
        if (proxyInfoRespBuilder_ == null) {
          proxyInfoRespBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.wangboo.cluster.protocol.L2cProto.L2CProxyInfoResp, com.wangboo.cluster.protocol.L2cProto.L2CProxyInfoResp.Builder, com.wangboo.cluster.protocol.L2cProto.L2CProxyInfoRespOrBuilder>(
                  proxyInfoResp_,
                  getParentForChildren(),
                  isClean());
          proxyInfoResp_ = null;
        }
        return proxyInfoRespBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:L2CMessage)
    }
    
    static {
      defaultInstance = new L2CMessage(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:L2CMessage)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_C2LMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_C2LMessage_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_L2CProxyInfoResp_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_L2CProxyInfoResp_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_L2CMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_L2CMessage_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022login2client.proto\032\013msgid.proto\"#\n\nC2L" +
      "Message\022\025\n\005msgId\030\001 \002(\0162\006.MsgId\"J\n\020L2CPro" +
      "xyInfoResp\022\r\n\005state\030\001 \002(\005\022\n\n\002ip\030\002 \001(\t\022\014\n" +
      "\004port\030\003 \001(\005\022\r\n\005count\030\004 \001(\005\"M\n\nL2CMessage" +
      "\022\025\n\005msgId\030\001 \002(\0162\006.MsgId\022(\n\rproxyInfoResp" +
      "\030\002 \001(\0132\021.L2CProxyInfoRespB(\n\034com.wangboo" +
      ".cluster.protocolB\010L2cProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_C2LMessage_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_C2LMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_C2LMessage_descriptor,
              new java.lang.String[] { "MsgId", },
              com.wangboo.cluster.protocol.L2cProto.C2LMessage.class,
              com.wangboo.cluster.protocol.L2cProto.C2LMessage.Builder.class);
          internal_static_L2CProxyInfoResp_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_L2CProxyInfoResp_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_L2CProxyInfoResp_descriptor,
              new java.lang.String[] { "State", "Ip", "Port", "Count", },
              com.wangboo.cluster.protocol.L2cProto.L2CProxyInfoResp.class,
              com.wangboo.cluster.protocol.L2cProto.L2CProxyInfoResp.Builder.class);
          internal_static_L2CMessage_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_L2CMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_L2CMessage_descriptor,
              new java.lang.String[] { "MsgId", "ProxyInfoResp", },
              com.wangboo.cluster.protocol.L2cProto.L2CMessage.class,
              com.wangboo.cluster.protocol.L2cProto.L2CMessage.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.wangboo.cluster.protocol.MsgIdProto.getDescriptor(),
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
