// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msgid.proto

package com.wangboo.cluster.protocol;

public final class MsgIdProto {
  private MsgIdProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public enum MsgId
      implements com.google.protobuf.ProtocolMessageEnum {
    Common_HeartBeat(0, 1),
    Common_HeartBeatResp(1, 2),
    Common_ProxyStateQuery(2, 3),
    Common_ProxyStateResp(3, 4),
    Common_PlayerLeave(4, 5),
    Common_talk(5, 6),
    Common_g2cMsg(6, 7),
    C2L_HeartBeat(7, 1001),
    C2L_ProxyInfoQuery(8, 1002),
    L2C_HeartBeat(9, 2001),
    L2C_ProxyInfoResp(10, 2002),
    Client2Gate_Login(11, 10001),
    Gate2Client_LoginResp(12, 20001),
    Gate2Client_Talk(13, 20002),
    P2Center_JoinRoom(14, 80001),
    P2Center_LeaveRoom(15, 80002),
    ;
    
    public static final int Common_HeartBeat_VALUE = 1;
    public static final int Common_HeartBeatResp_VALUE = 2;
    public static final int Common_ProxyStateQuery_VALUE = 3;
    public static final int Common_ProxyStateResp_VALUE = 4;
    public static final int Common_PlayerLeave_VALUE = 5;
    public static final int Common_talk_VALUE = 6;
    public static final int Common_g2cMsg_VALUE = 7;
    public static final int C2L_HeartBeat_VALUE = 1001;
    public static final int C2L_ProxyInfoQuery_VALUE = 1002;
    public static final int L2C_HeartBeat_VALUE = 2001;
    public static final int L2C_ProxyInfoResp_VALUE = 2002;
    public static final int Client2Gate_Login_VALUE = 10001;
    public static final int Gate2Client_LoginResp_VALUE = 20001;
    public static final int Gate2Client_Talk_VALUE = 20002;
    public static final int P2Center_JoinRoom_VALUE = 80001;
    public static final int P2Center_LeaveRoom_VALUE = 80002;
    
    
    public final int getNumber() { return value; }
    
    public static MsgId valueOf(int value) {
      switch (value) {
        case 1: return Common_HeartBeat;
        case 2: return Common_HeartBeatResp;
        case 3: return Common_ProxyStateQuery;
        case 4: return Common_ProxyStateResp;
        case 5: return Common_PlayerLeave;
        case 6: return Common_talk;
        case 7: return Common_g2cMsg;
        case 1001: return C2L_HeartBeat;
        case 1002: return C2L_ProxyInfoQuery;
        case 2001: return L2C_HeartBeat;
        case 2002: return L2C_ProxyInfoResp;
        case 10001: return Client2Gate_Login;
        case 20001: return Gate2Client_LoginResp;
        case 20002: return Gate2Client_Talk;
        case 80001: return P2Center_JoinRoom;
        case 80002: return P2Center_LeaveRoom;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<MsgId>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<MsgId>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MsgId>() {
            public MsgId findValueByNumber(int number) {
              return MsgId.valueOf(number);
            }
          };
    
    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.wangboo.cluster.protocol.MsgIdProto.getDescriptor().getEnumTypes().get(0);
    }
    
    private static final MsgId[] VALUES = {
      Common_HeartBeat, Common_HeartBeatResp, Common_ProxyStateQuery, Common_ProxyStateResp, Common_PlayerLeave, Common_talk, Common_g2cMsg, C2L_HeartBeat, C2L_ProxyInfoQuery, L2C_HeartBeat, L2C_ProxyInfoResp, Client2Gate_Login, Gate2Client_LoginResp, Gate2Client_Talk, P2Center_JoinRoom, P2Center_LeaveRoom, 
    };
    
    public static MsgId valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }
    
    private final int index;
    private final int value;
    
    private MsgId(int index, int value) {
      this.index = index;
      this.value = value;
    }
    
    // @@protoc_insertion_point(enum_scope:MsgId)
  }
  
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013msgid.proto*\203\003\n\005MsgId\022\024\n\020Common_HeartB" +
      "eat\020\001\022\030\n\024Common_HeartBeatResp\020\002\022\032\n\026Commo" +
      "n_ProxyStateQuery\020\003\022\031\n\025Common_ProxyState" +
      "Resp\020\004\022\026\n\022Common_PlayerLeave\020\005\022\017\n\013Common" +
      "_talk\020\006\022\021\n\rCommon_g2cMsg\020\007\022\022\n\rC2L_HeartB" +
      "eat\020\351\007\022\027\n\022C2L_ProxyInfoQuery\020\352\007\022\022\n\rL2C_H" +
      "eartBeat\020\321\017\022\026\n\021L2C_ProxyInfoResp\020\322\017\022\026\n\021C" +
      "lient2Gate_Login\020\221N\022\033\n\025Gate2Client_Login" +
      "Resp\020\241\234\001\022\026\n\020Gate2Client_Talk\020\242\234\001\022\027\n\021P2Ce" +
      "nter_JoinRoom\020\201\361\004\022\030\n\022P2Center_LeaveRoom\020",
      "\202\361\004B*\n\034com.wangboo.cluster.protocolB\nMsg" +
      "IdProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
