// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg.proto

package com.wangboo.cluster.protocol;

public final class Proto {
  private Proto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface P2CenterJoinRoomOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string roomNo = 1;
    boolean hasRoomNo();
    String getRoomNo();
  }
  public static final class P2CenterJoinRoom extends
      com.google.protobuf.GeneratedMessage
      implements P2CenterJoinRoomOrBuilder {
    // Use P2CenterJoinRoom.newBuilder() to construct.
    private P2CenterJoinRoom(Builder builder) {
      super(builder);
    }
    private P2CenterJoinRoom(boolean noInit) {}
    
    private static final P2CenterJoinRoom defaultInstance;
    public static P2CenterJoinRoom getDefaultInstance() {
      return defaultInstance;
    }
    
    public P2CenterJoinRoom getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.wangboo.cluster.protocol.Proto.internal_static_P2CenterJoinRoom_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.wangboo.cluster.protocol.Proto.internal_static_P2CenterJoinRoom_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string roomNo = 1;
    public static final int ROOMNO_FIELD_NUMBER = 1;
    private java.lang.Object roomNo_;
    public boolean hasRoomNo() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getRoomNo() {
      java.lang.Object ref = roomNo_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          roomNo_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getRoomNoBytes() {
      java.lang.Object ref = roomNo_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        roomNo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      roomNo_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasRoomNo()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getRoomNoBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getRoomNoBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.wangboo.cluster.protocol.Proto.P2CenterJoinRoom parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.wangboo.cluster.protocol.Proto.P2CenterJoinRoom parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.wangboo.cluster.protocol.Proto.P2CenterJoinRoom parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.wangboo.cluster.protocol.Proto.P2CenterJoinRoom parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.wangboo.cluster.protocol.Proto.P2CenterJoinRoom parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.wangboo.cluster.protocol.Proto.P2CenterJoinRoom parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.wangboo.cluster.protocol.Proto.P2CenterJoinRoom parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.wangboo.cluster.protocol.Proto.P2CenterJoinRoom parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.wangboo.cluster.protocol.Proto.P2CenterJoinRoom parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.wangboo.cluster.protocol.Proto.P2CenterJoinRoom parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.wangboo.cluster.protocol.Proto.P2CenterJoinRoom prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.wangboo.cluster.protocol.Proto.P2CenterJoinRoomOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.wangboo.cluster.protocol.Proto.internal_static_P2CenterJoinRoom_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.wangboo.cluster.protocol.Proto.internal_static_P2CenterJoinRoom_fieldAccessorTable;
      }
      
      // Construct using com.wangboo.cluster.protocol.Proto.P2CenterJoinRoom.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        roomNo_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.wangboo.cluster.protocol.Proto.P2CenterJoinRoom.getDescriptor();
      }
      
      public com.wangboo.cluster.protocol.Proto.P2CenterJoinRoom getDefaultInstanceForType() {
        return com.wangboo.cluster.protocol.Proto.P2CenterJoinRoom.getDefaultInstance();
      }
      
      public com.wangboo.cluster.protocol.Proto.P2CenterJoinRoom build() {
        com.wangboo.cluster.protocol.Proto.P2CenterJoinRoom result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.wangboo.cluster.protocol.Proto.P2CenterJoinRoom buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.wangboo.cluster.protocol.Proto.P2CenterJoinRoom result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.wangboo.cluster.protocol.Proto.P2CenterJoinRoom buildPartial() {
        com.wangboo.cluster.protocol.Proto.P2CenterJoinRoom result = new com.wangboo.cluster.protocol.Proto.P2CenterJoinRoom(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.roomNo_ = roomNo_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.wangboo.cluster.protocol.Proto.P2CenterJoinRoom) {
          return mergeFrom((com.wangboo.cluster.protocol.Proto.P2CenterJoinRoom)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.wangboo.cluster.protocol.Proto.P2CenterJoinRoom other) {
        if (other == com.wangboo.cluster.protocol.Proto.P2CenterJoinRoom.getDefaultInstance()) return this;
        if (other.hasRoomNo()) {
          setRoomNo(other.getRoomNo());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasRoomNo()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              roomNo_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string roomNo = 1;
      private java.lang.Object roomNo_ = "";
      public boolean hasRoomNo() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getRoomNo() {
        java.lang.Object ref = roomNo_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          roomNo_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setRoomNo(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        roomNo_ = value;
        onChanged();
        return this;
      }
      public Builder clearRoomNo() {
        bitField0_ = (bitField0_ & ~0x00000001);
        roomNo_ = getDefaultInstance().getRoomNo();
        onChanged();
        return this;
      }
      void setRoomNo(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        roomNo_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:P2CenterJoinRoom)
    }
    
    static {
      defaultInstance = new P2CenterJoinRoom(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:P2CenterJoinRoom)
  }
  
  public interface P2CenterMsgOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required .MsgId msgId = 1;
    boolean hasMsgId();
    com.wangboo.cluster.protocol.MsgIdProto.MsgId getMsgId();
    
    // required string from = 2;
    boolean hasFrom();
    String getFrom();
    
    // optional int32 roleId = 3;
    boolean hasRoleId();
    int getRoleId();
    
    // optional .P2CenterJoinRoom joinRoom = 10;
    boolean hasJoinRoom();
    com.wangboo.cluster.protocol.Proto.P2CenterJoinRoom getJoinRoom();
    com.wangboo.cluster.protocol.Proto.P2CenterJoinRoomOrBuilder getJoinRoomOrBuilder();
  }
  public static final class P2CenterMsg extends
      com.google.protobuf.GeneratedMessage
      implements P2CenterMsgOrBuilder {
    // Use P2CenterMsg.newBuilder() to construct.
    private P2CenterMsg(Builder builder) {
      super(builder);
    }
    private P2CenterMsg(boolean noInit) {}
    
    private static final P2CenterMsg defaultInstance;
    public static P2CenterMsg getDefaultInstance() {
      return defaultInstance;
    }
    
    public P2CenterMsg getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.wangboo.cluster.protocol.Proto.internal_static_P2CenterMsg_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.wangboo.cluster.protocol.Proto.internal_static_P2CenterMsg_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required .MsgId msgId = 1;
    public static final int MSGID_FIELD_NUMBER = 1;
    private com.wangboo.cluster.protocol.MsgIdProto.MsgId msgId_;
    public boolean hasMsgId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public com.wangboo.cluster.protocol.MsgIdProto.MsgId getMsgId() {
      return msgId_;
    }
    
    // required string from = 2;
    public static final int FROM_FIELD_NUMBER = 2;
    private java.lang.Object from_;
    public boolean hasFrom() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getFrom() {
      java.lang.Object ref = from_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          from_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getFromBytes() {
      java.lang.Object ref = from_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        from_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional int32 roleId = 3;
    public static final int ROLEID_FIELD_NUMBER = 3;
    private int roleId_;
    public boolean hasRoleId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public int getRoleId() {
      return roleId_;
    }
    
    // optional .P2CenterJoinRoom joinRoom = 10;
    public static final int JOINROOM_FIELD_NUMBER = 10;
    private com.wangboo.cluster.protocol.Proto.P2CenterJoinRoom joinRoom_;
    public boolean hasJoinRoom() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public com.wangboo.cluster.protocol.Proto.P2CenterJoinRoom getJoinRoom() {
      return joinRoom_;
    }
    public com.wangboo.cluster.protocol.Proto.P2CenterJoinRoomOrBuilder getJoinRoomOrBuilder() {
      return joinRoom_;
    }
    
    private void initFields() {
      msgId_ = com.wangboo.cluster.protocol.MsgIdProto.MsgId.Common_HeartBeat;
      from_ = "";
      roleId_ = 0;
      joinRoom_ = com.wangboo.cluster.protocol.Proto.P2CenterJoinRoom.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasMsgId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasFrom()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasJoinRoom()) {
        if (!getJoinRoom().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, msgId_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getFromBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, roleId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeMessage(10, joinRoom_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, msgId_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getFromBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, roleId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(10, joinRoom_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.wangboo.cluster.protocol.Proto.P2CenterMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.wangboo.cluster.protocol.Proto.P2CenterMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.wangboo.cluster.protocol.Proto.P2CenterMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.wangboo.cluster.protocol.Proto.P2CenterMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.wangboo.cluster.protocol.Proto.P2CenterMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.wangboo.cluster.protocol.Proto.P2CenterMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.wangboo.cluster.protocol.Proto.P2CenterMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.wangboo.cluster.protocol.Proto.P2CenterMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.wangboo.cluster.protocol.Proto.P2CenterMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.wangboo.cluster.protocol.Proto.P2CenterMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.wangboo.cluster.protocol.Proto.P2CenterMsg prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.wangboo.cluster.protocol.Proto.P2CenterMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.wangboo.cluster.protocol.Proto.internal_static_P2CenterMsg_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.wangboo.cluster.protocol.Proto.internal_static_P2CenterMsg_fieldAccessorTable;
      }
      
      // Construct using com.wangboo.cluster.protocol.Proto.P2CenterMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getJoinRoomFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        msgId_ = com.wangboo.cluster.protocol.MsgIdProto.MsgId.Common_HeartBeat;
        bitField0_ = (bitField0_ & ~0x00000001);
        from_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        roleId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        if (joinRoomBuilder_ == null) {
          joinRoom_ = com.wangboo.cluster.protocol.Proto.P2CenterJoinRoom.getDefaultInstance();
        } else {
          joinRoomBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.wangboo.cluster.protocol.Proto.P2CenterMsg.getDescriptor();
      }
      
      public com.wangboo.cluster.protocol.Proto.P2CenterMsg getDefaultInstanceForType() {
        return com.wangboo.cluster.protocol.Proto.P2CenterMsg.getDefaultInstance();
      }
      
      public com.wangboo.cluster.protocol.Proto.P2CenterMsg build() {
        com.wangboo.cluster.protocol.Proto.P2CenterMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.wangboo.cluster.protocol.Proto.P2CenterMsg buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.wangboo.cluster.protocol.Proto.P2CenterMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.wangboo.cluster.protocol.Proto.P2CenterMsg buildPartial() {
        com.wangboo.cluster.protocol.Proto.P2CenterMsg result = new com.wangboo.cluster.protocol.Proto.P2CenterMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.msgId_ = msgId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.from_ = from_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.roleId_ = roleId_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        if (joinRoomBuilder_ == null) {
          result.joinRoom_ = joinRoom_;
        } else {
          result.joinRoom_ = joinRoomBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.wangboo.cluster.protocol.Proto.P2CenterMsg) {
          return mergeFrom((com.wangboo.cluster.protocol.Proto.P2CenterMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.wangboo.cluster.protocol.Proto.P2CenterMsg other) {
        if (other == com.wangboo.cluster.protocol.Proto.P2CenterMsg.getDefaultInstance()) return this;
        if (other.hasMsgId()) {
          setMsgId(other.getMsgId());
        }
        if (other.hasFrom()) {
          setFrom(other.getFrom());
        }
        if (other.hasRoleId()) {
          setRoleId(other.getRoleId());
        }
        if (other.hasJoinRoom()) {
          mergeJoinRoom(other.getJoinRoom());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasMsgId()) {
          
          return false;
        }
        if (!hasFrom()) {
          
          return false;
        }
        if (hasJoinRoom()) {
          if (!getJoinRoom().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.wangboo.cluster.protocol.MsgIdProto.MsgId value = com.wangboo.cluster.protocol.MsgIdProto.MsgId.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                msgId_ = value;
              }
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              from_ = input.readBytes();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              roleId_ = input.readInt32();
              break;
            }
            case 82: {
              com.wangboo.cluster.protocol.Proto.P2CenterJoinRoom.Builder subBuilder = com.wangboo.cluster.protocol.Proto.P2CenterJoinRoom.newBuilder();
              if (hasJoinRoom()) {
                subBuilder.mergeFrom(getJoinRoom());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setJoinRoom(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required .MsgId msgId = 1;
      private com.wangboo.cluster.protocol.MsgIdProto.MsgId msgId_ = com.wangboo.cluster.protocol.MsgIdProto.MsgId.Common_HeartBeat;
      public boolean hasMsgId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public com.wangboo.cluster.protocol.MsgIdProto.MsgId getMsgId() {
        return msgId_;
      }
      public Builder setMsgId(com.wangboo.cluster.protocol.MsgIdProto.MsgId value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        msgId_ = value;
        onChanged();
        return this;
      }
      public Builder clearMsgId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        msgId_ = com.wangboo.cluster.protocol.MsgIdProto.MsgId.Common_HeartBeat;
        onChanged();
        return this;
      }
      
      // required string from = 2;
      private java.lang.Object from_ = "";
      public boolean hasFrom() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getFrom() {
        java.lang.Object ref = from_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          from_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setFrom(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        from_ = value;
        onChanged();
        return this;
      }
      public Builder clearFrom() {
        bitField0_ = (bitField0_ & ~0x00000002);
        from_ = getDefaultInstance().getFrom();
        onChanged();
        return this;
      }
      void setFrom(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        from_ = value;
        onChanged();
      }
      
      // optional int32 roleId = 3;
      private int roleId_ ;
      public boolean hasRoleId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getRoleId() {
        return roleId_;
      }
      public Builder setRoleId(int value) {
        bitField0_ |= 0x00000004;
        roleId_ = value;
        onChanged();
        return this;
      }
      public Builder clearRoleId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        roleId_ = 0;
        onChanged();
        return this;
      }
      
      // optional .P2CenterJoinRoom joinRoom = 10;
      private com.wangboo.cluster.protocol.Proto.P2CenterJoinRoom joinRoom_ = com.wangboo.cluster.protocol.Proto.P2CenterJoinRoom.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.wangboo.cluster.protocol.Proto.P2CenterJoinRoom, com.wangboo.cluster.protocol.Proto.P2CenterJoinRoom.Builder, com.wangboo.cluster.protocol.Proto.P2CenterJoinRoomOrBuilder> joinRoomBuilder_;
      public boolean hasJoinRoom() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public com.wangboo.cluster.protocol.Proto.P2CenterJoinRoom getJoinRoom() {
        if (joinRoomBuilder_ == null) {
          return joinRoom_;
        } else {
          return joinRoomBuilder_.getMessage();
        }
      }
      public Builder setJoinRoom(com.wangboo.cluster.protocol.Proto.P2CenterJoinRoom value) {
        if (joinRoomBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          joinRoom_ = value;
          onChanged();
        } else {
          joinRoomBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      public Builder setJoinRoom(
          com.wangboo.cluster.protocol.Proto.P2CenterJoinRoom.Builder builderForValue) {
        if (joinRoomBuilder_ == null) {
          joinRoom_ = builderForValue.build();
          onChanged();
        } else {
          joinRoomBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      public Builder mergeJoinRoom(com.wangboo.cluster.protocol.Proto.P2CenterJoinRoom value) {
        if (joinRoomBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008) &&
              joinRoom_ != com.wangboo.cluster.protocol.Proto.P2CenterJoinRoom.getDefaultInstance()) {
            joinRoom_ =
              com.wangboo.cluster.protocol.Proto.P2CenterJoinRoom.newBuilder(joinRoom_).mergeFrom(value).buildPartial();
          } else {
            joinRoom_ = value;
          }
          onChanged();
        } else {
          joinRoomBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      public Builder clearJoinRoom() {
        if (joinRoomBuilder_ == null) {
          joinRoom_ = com.wangboo.cluster.protocol.Proto.P2CenterJoinRoom.getDefaultInstance();
          onChanged();
        } else {
          joinRoomBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      public com.wangboo.cluster.protocol.Proto.P2CenterJoinRoom.Builder getJoinRoomBuilder() {
        bitField0_ |= 0x00000008;
        onChanged();
        return getJoinRoomFieldBuilder().getBuilder();
      }
      public com.wangboo.cluster.protocol.Proto.P2CenterJoinRoomOrBuilder getJoinRoomOrBuilder() {
        if (joinRoomBuilder_ != null) {
          return joinRoomBuilder_.getMessageOrBuilder();
        } else {
          return joinRoom_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          com.wangboo.cluster.protocol.Proto.P2CenterJoinRoom, com.wangboo.cluster.protocol.Proto.P2CenterJoinRoom.Builder, com.wangboo.cluster.protocol.Proto.P2CenterJoinRoomOrBuilder> 
          getJoinRoomFieldBuilder() {
        if (joinRoomBuilder_ == null) {
          joinRoomBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.wangboo.cluster.protocol.Proto.P2CenterJoinRoom, com.wangboo.cluster.protocol.Proto.P2CenterJoinRoom.Builder, com.wangboo.cluster.protocol.Proto.P2CenterJoinRoomOrBuilder>(
                  joinRoom_,
                  getParentForChildren(),
                  isClean());
          joinRoom_ = null;
        }
        return joinRoomBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:P2CenterMsg)
    }
    
    static {
      defaultInstance = new P2CenterMsg(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:P2CenterMsg)
  }
  
  public interface Gate2Match_MatchRoomOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int32 roleid = 1;
    boolean hasRoleid();
    int getRoleid();
    
    // required string name = 2;
    boolean hasName();
    String getName();
    
    // required int32 gold = 3;
    boolean hasGold();
    int getGold();
  }
  public static final class Gate2Match_MatchRoom extends
      com.google.protobuf.GeneratedMessage
      implements Gate2Match_MatchRoomOrBuilder {
    // Use Gate2Match_MatchRoom.newBuilder() to construct.
    private Gate2Match_MatchRoom(Builder builder) {
      super(builder);
    }
    private Gate2Match_MatchRoom(boolean noInit) {}
    
    private static final Gate2Match_MatchRoom defaultInstance;
    public static Gate2Match_MatchRoom getDefaultInstance() {
      return defaultInstance;
    }
    
    public Gate2Match_MatchRoom getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.wangboo.cluster.protocol.Proto.internal_static_Gate2Match_MatchRoom_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.wangboo.cluster.protocol.Proto.internal_static_Gate2Match_MatchRoom_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int32 roleid = 1;
    public static final int ROLEID_FIELD_NUMBER = 1;
    private int roleid_;
    public boolean hasRoleid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getRoleid() {
      return roleid_;
    }
    
    // required string name = 2;
    public static final int NAME_FIELD_NUMBER = 2;
    private java.lang.Object name_;
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          name_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required int32 gold = 3;
    public static final int GOLD_FIELD_NUMBER = 3;
    private int gold_;
    public boolean hasGold() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public int getGold() {
      return gold_;
    }
    
    private void initFields() {
      roleid_ = 0;
      name_ = "";
      gold_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasRoleid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasGold()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, roleid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, gold_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, roleid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, gold_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.wangboo.cluster.protocol.Proto.Gate2Match_MatchRoom parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.wangboo.cluster.protocol.Proto.Gate2Match_MatchRoom parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.wangboo.cluster.protocol.Proto.Gate2Match_MatchRoom parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.wangboo.cluster.protocol.Proto.Gate2Match_MatchRoom parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.wangboo.cluster.protocol.Proto.Gate2Match_MatchRoom parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.wangboo.cluster.protocol.Proto.Gate2Match_MatchRoom parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.wangboo.cluster.protocol.Proto.Gate2Match_MatchRoom parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.wangboo.cluster.protocol.Proto.Gate2Match_MatchRoom parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.wangboo.cluster.protocol.Proto.Gate2Match_MatchRoom parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.wangboo.cluster.protocol.Proto.Gate2Match_MatchRoom parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.wangboo.cluster.protocol.Proto.Gate2Match_MatchRoom prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.wangboo.cluster.protocol.Proto.Gate2Match_MatchRoomOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.wangboo.cluster.protocol.Proto.internal_static_Gate2Match_MatchRoom_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.wangboo.cluster.protocol.Proto.internal_static_Gate2Match_MatchRoom_fieldAccessorTable;
      }
      
      // Construct using com.wangboo.cluster.protocol.Proto.Gate2Match_MatchRoom.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        roleid_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        gold_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.wangboo.cluster.protocol.Proto.Gate2Match_MatchRoom.getDescriptor();
      }
      
      public com.wangboo.cluster.protocol.Proto.Gate2Match_MatchRoom getDefaultInstanceForType() {
        return com.wangboo.cluster.protocol.Proto.Gate2Match_MatchRoom.getDefaultInstance();
      }
      
      public com.wangboo.cluster.protocol.Proto.Gate2Match_MatchRoom build() {
        com.wangboo.cluster.protocol.Proto.Gate2Match_MatchRoom result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.wangboo.cluster.protocol.Proto.Gate2Match_MatchRoom buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.wangboo.cluster.protocol.Proto.Gate2Match_MatchRoom result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.wangboo.cluster.protocol.Proto.Gate2Match_MatchRoom buildPartial() {
        com.wangboo.cluster.protocol.Proto.Gate2Match_MatchRoom result = new com.wangboo.cluster.protocol.Proto.Gate2Match_MatchRoom(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.roleid_ = roleid_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.gold_ = gold_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.wangboo.cluster.protocol.Proto.Gate2Match_MatchRoom) {
          return mergeFrom((com.wangboo.cluster.protocol.Proto.Gate2Match_MatchRoom)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.wangboo.cluster.protocol.Proto.Gate2Match_MatchRoom other) {
        if (other == com.wangboo.cluster.protocol.Proto.Gate2Match_MatchRoom.getDefaultInstance()) return this;
        if (other.hasRoleid()) {
          setRoleid(other.getRoleid());
        }
        if (other.hasName()) {
          setName(other.getName());
        }
        if (other.hasGold()) {
          setGold(other.getGold());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasRoleid()) {
          
          return false;
        }
        if (!hasName()) {
          
          return false;
        }
        if (!hasGold()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              roleid_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              name_ = input.readBytes();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              gold_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 roleid = 1;
      private int roleid_ ;
      public boolean hasRoleid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getRoleid() {
        return roleid_;
      }
      public Builder setRoleid(int value) {
        bitField0_ |= 0x00000001;
        roleid_ = value;
        onChanged();
        return this;
      }
      public Builder clearRoleid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        roleid_ = 0;
        onChanged();
        return this;
      }
      
      // required string name = 2;
      private java.lang.Object name_ = "";
      public boolean hasName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      void setName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
      }
      
      // required int32 gold = 3;
      private int gold_ ;
      public boolean hasGold() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getGold() {
        return gold_;
      }
      public Builder setGold(int value) {
        bitField0_ |= 0x00000004;
        gold_ = value;
        onChanged();
        return this;
      }
      public Builder clearGold() {
        bitField0_ = (bitField0_ & ~0x00000004);
        gold_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:Gate2Match_MatchRoom)
    }
    
    static {
      defaultInstance = new Gate2Match_MatchRoom(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:Gate2Match_MatchRoom)
  }
  
  public interface Gate2MatchMsgOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required .MsgId msgId = 1;
    boolean hasMsgId();
    com.wangboo.cluster.protocol.MsgIdProto.MsgId getMsgId();
    
    // required string from = 2;
    boolean hasFrom();
    String getFrom();
    
    // optional .Gate2Match_MatchRoom matchroom = 3;
    boolean hasMatchroom();
    com.wangboo.cluster.protocol.Proto.Gate2Match_MatchRoom getMatchroom();
    com.wangboo.cluster.protocol.Proto.Gate2Match_MatchRoomOrBuilder getMatchroomOrBuilder();
  }
  public static final class Gate2MatchMsg extends
      com.google.protobuf.GeneratedMessage
      implements Gate2MatchMsgOrBuilder {
    // Use Gate2MatchMsg.newBuilder() to construct.
    private Gate2MatchMsg(Builder builder) {
      super(builder);
    }
    private Gate2MatchMsg(boolean noInit) {}
    
    private static final Gate2MatchMsg defaultInstance;
    public static Gate2MatchMsg getDefaultInstance() {
      return defaultInstance;
    }
    
    public Gate2MatchMsg getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.wangboo.cluster.protocol.Proto.internal_static_Gate2MatchMsg_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.wangboo.cluster.protocol.Proto.internal_static_Gate2MatchMsg_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required .MsgId msgId = 1;
    public static final int MSGID_FIELD_NUMBER = 1;
    private com.wangboo.cluster.protocol.MsgIdProto.MsgId msgId_;
    public boolean hasMsgId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public com.wangboo.cluster.protocol.MsgIdProto.MsgId getMsgId() {
      return msgId_;
    }
    
    // required string from = 2;
    public static final int FROM_FIELD_NUMBER = 2;
    private java.lang.Object from_;
    public boolean hasFrom() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getFrom() {
      java.lang.Object ref = from_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          from_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getFromBytes() {
      java.lang.Object ref = from_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        from_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional .Gate2Match_MatchRoom matchroom = 3;
    public static final int MATCHROOM_FIELD_NUMBER = 3;
    private com.wangboo.cluster.protocol.Proto.Gate2Match_MatchRoom matchroom_;
    public boolean hasMatchroom() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public com.wangboo.cluster.protocol.Proto.Gate2Match_MatchRoom getMatchroom() {
      return matchroom_;
    }
    public com.wangboo.cluster.protocol.Proto.Gate2Match_MatchRoomOrBuilder getMatchroomOrBuilder() {
      return matchroom_;
    }
    
    private void initFields() {
      msgId_ = com.wangboo.cluster.protocol.MsgIdProto.MsgId.Common_HeartBeat;
      from_ = "";
      matchroom_ = com.wangboo.cluster.protocol.Proto.Gate2Match_MatchRoom.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasMsgId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasFrom()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasMatchroom()) {
        if (!getMatchroom().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, msgId_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getFromBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(3, matchroom_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, msgId_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getFromBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, matchroom_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.wangboo.cluster.protocol.Proto.Gate2MatchMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.wangboo.cluster.protocol.Proto.Gate2MatchMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.wangboo.cluster.protocol.Proto.Gate2MatchMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.wangboo.cluster.protocol.Proto.Gate2MatchMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.wangboo.cluster.protocol.Proto.Gate2MatchMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.wangboo.cluster.protocol.Proto.Gate2MatchMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.wangboo.cluster.protocol.Proto.Gate2MatchMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.wangboo.cluster.protocol.Proto.Gate2MatchMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.wangboo.cluster.protocol.Proto.Gate2MatchMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.wangboo.cluster.protocol.Proto.Gate2MatchMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.wangboo.cluster.protocol.Proto.Gate2MatchMsg prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.wangboo.cluster.protocol.Proto.Gate2MatchMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.wangboo.cluster.protocol.Proto.internal_static_Gate2MatchMsg_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.wangboo.cluster.protocol.Proto.internal_static_Gate2MatchMsg_fieldAccessorTable;
      }
      
      // Construct using com.wangboo.cluster.protocol.Proto.Gate2MatchMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getMatchroomFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        msgId_ = com.wangboo.cluster.protocol.MsgIdProto.MsgId.Common_HeartBeat;
        bitField0_ = (bitField0_ & ~0x00000001);
        from_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        if (matchroomBuilder_ == null) {
          matchroom_ = com.wangboo.cluster.protocol.Proto.Gate2Match_MatchRoom.getDefaultInstance();
        } else {
          matchroomBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.wangboo.cluster.protocol.Proto.Gate2MatchMsg.getDescriptor();
      }
      
      public com.wangboo.cluster.protocol.Proto.Gate2MatchMsg getDefaultInstanceForType() {
        return com.wangboo.cluster.protocol.Proto.Gate2MatchMsg.getDefaultInstance();
      }
      
      public com.wangboo.cluster.protocol.Proto.Gate2MatchMsg build() {
        com.wangboo.cluster.protocol.Proto.Gate2MatchMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.wangboo.cluster.protocol.Proto.Gate2MatchMsg buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.wangboo.cluster.protocol.Proto.Gate2MatchMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.wangboo.cluster.protocol.Proto.Gate2MatchMsg buildPartial() {
        com.wangboo.cluster.protocol.Proto.Gate2MatchMsg result = new com.wangboo.cluster.protocol.Proto.Gate2MatchMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.msgId_ = msgId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.from_ = from_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (matchroomBuilder_ == null) {
          result.matchroom_ = matchroom_;
        } else {
          result.matchroom_ = matchroomBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.wangboo.cluster.protocol.Proto.Gate2MatchMsg) {
          return mergeFrom((com.wangboo.cluster.protocol.Proto.Gate2MatchMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.wangboo.cluster.protocol.Proto.Gate2MatchMsg other) {
        if (other == com.wangboo.cluster.protocol.Proto.Gate2MatchMsg.getDefaultInstance()) return this;
        if (other.hasMsgId()) {
          setMsgId(other.getMsgId());
        }
        if (other.hasFrom()) {
          setFrom(other.getFrom());
        }
        if (other.hasMatchroom()) {
          mergeMatchroom(other.getMatchroom());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasMsgId()) {
          
          return false;
        }
        if (!hasFrom()) {
          
          return false;
        }
        if (hasMatchroom()) {
          if (!getMatchroom().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.wangboo.cluster.protocol.MsgIdProto.MsgId value = com.wangboo.cluster.protocol.MsgIdProto.MsgId.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                msgId_ = value;
              }
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              from_ = input.readBytes();
              break;
            }
            case 26: {
              com.wangboo.cluster.protocol.Proto.Gate2Match_MatchRoom.Builder subBuilder = com.wangboo.cluster.protocol.Proto.Gate2Match_MatchRoom.newBuilder();
              if (hasMatchroom()) {
                subBuilder.mergeFrom(getMatchroom());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setMatchroom(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required .MsgId msgId = 1;
      private com.wangboo.cluster.protocol.MsgIdProto.MsgId msgId_ = com.wangboo.cluster.protocol.MsgIdProto.MsgId.Common_HeartBeat;
      public boolean hasMsgId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public com.wangboo.cluster.protocol.MsgIdProto.MsgId getMsgId() {
        return msgId_;
      }
      public Builder setMsgId(com.wangboo.cluster.protocol.MsgIdProto.MsgId value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        msgId_ = value;
        onChanged();
        return this;
      }
      public Builder clearMsgId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        msgId_ = com.wangboo.cluster.protocol.MsgIdProto.MsgId.Common_HeartBeat;
        onChanged();
        return this;
      }
      
      // required string from = 2;
      private java.lang.Object from_ = "";
      public boolean hasFrom() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getFrom() {
        java.lang.Object ref = from_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          from_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setFrom(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        from_ = value;
        onChanged();
        return this;
      }
      public Builder clearFrom() {
        bitField0_ = (bitField0_ & ~0x00000002);
        from_ = getDefaultInstance().getFrom();
        onChanged();
        return this;
      }
      void setFrom(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        from_ = value;
        onChanged();
      }
      
      // optional .Gate2Match_MatchRoom matchroom = 3;
      private com.wangboo.cluster.protocol.Proto.Gate2Match_MatchRoom matchroom_ = com.wangboo.cluster.protocol.Proto.Gate2Match_MatchRoom.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.wangboo.cluster.protocol.Proto.Gate2Match_MatchRoom, com.wangboo.cluster.protocol.Proto.Gate2Match_MatchRoom.Builder, com.wangboo.cluster.protocol.Proto.Gate2Match_MatchRoomOrBuilder> matchroomBuilder_;
      public boolean hasMatchroom() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public com.wangboo.cluster.protocol.Proto.Gate2Match_MatchRoom getMatchroom() {
        if (matchroomBuilder_ == null) {
          return matchroom_;
        } else {
          return matchroomBuilder_.getMessage();
        }
      }
      public Builder setMatchroom(com.wangboo.cluster.protocol.Proto.Gate2Match_MatchRoom value) {
        if (matchroomBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          matchroom_ = value;
          onChanged();
        } else {
          matchroomBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      public Builder setMatchroom(
          com.wangboo.cluster.protocol.Proto.Gate2Match_MatchRoom.Builder builderForValue) {
        if (matchroomBuilder_ == null) {
          matchroom_ = builderForValue.build();
          onChanged();
        } else {
          matchroomBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      public Builder mergeMatchroom(com.wangboo.cluster.protocol.Proto.Gate2Match_MatchRoom value) {
        if (matchroomBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              matchroom_ != com.wangboo.cluster.protocol.Proto.Gate2Match_MatchRoom.getDefaultInstance()) {
            matchroom_ =
              com.wangboo.cluster.protocol.Proto.Gate2Match_MatchRoom.newBuilder(matchroom_).mergeFrom(value).buildPartial();
          } else {
            matchroom_ = value;
          }
          onChanged();
        } else {
          matchroomBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      public Builder clearMatchroom() {
        if (matchroomBuilder_ == null) {
          matchroom_ = com.wangboo.cluster.protocol.Proto.Gate2Match_MatchRoom.getDefaultInstance();
          onChanged();
        } else {
          matchroomBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      public com.wangboo.cluster.protocol.Proto.Gate2Match_MatchRoom.Builder getMatchroomBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getMatchroomFieldBuilder().getBuilder();
      }
      public com.wangboo.cluster.protocol.Proto.Gate2Match_MatchRoomOrBuilder getMatchroomOrBuilder() {
        if (matchroomBuilder_ != null) {
          return matchroomBuilder_.getMessageOrBuilder();
        } else {
          return matchroom_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          com.wangboo.cluster.protocol.Proto.Gate2Match_MatchRoom, com.wangboo.cluster.protocol.Proto.Gate2Match_MatchRoom.Builder, com.wangboo.cluster.protocol.Proto.Gate2Match_MatchRoomOrBuilder> 
          getMatchroomFieldBuilder() {
        if (matchroomBuilder_ == null) {
          matchroomBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.wangboo.cluster.protocol.Proto.Gate2Match_MatchRoom, com.wangboo.cluster.protocol.Proto.Gate2Match_MatchRoom.Builder, com.wangboo.cluster.protocol.Proto.Gate2Match_MatchRoomOrBuilder>(
                  matchroom_,
                  getParentForChildren(),
                  isClean());
          matchroom_ = null;
        }
        return matchroomBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:Gate2MatchMsg)
    }
    
    static {
      defaultInstance = new Gate2MatchMsg(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:Gate2MatchMsg)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_P2CenterJoinRoom_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_P2CenterJoinRoom_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_P2CenterMsg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_P2CenterMsg_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Gate2Match_MatchRoom_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Gate2Match_MatchRoom_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Gate2MatchMsg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Gate2MatchMsg_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tmsg.proto\032\013msgid.proto\"\"\n\020P2CenterJoin" +
      "Room\022\016\n\006roomNo\030\001 \002(\t\"g\n\013P2CenterMsg\022\025\n\005m" +
      "sgId\030\001 \002(\0162\006.MsgId\022\014\n\004from\030\002 \002(\t\022\016\n\006role" +
      "Id\030\003 \001(\005\022#\n\010joinRoom\030\n \001(\0132\021.P2CenterJoi" +
      "nRoom\"B\n\024Gate2Match_MatchRoom\022\016\n\006roleid\030" +
      "\001 \002(\005\022\014\n\004name\030\002 \002(\t\022\014\n\004gold\030\003 \002(\005\"^\n\rGat" +
      "e2MatchMsg\022\025\n\005msgId\030\001 \002(\0162\006.MsgId\022\014\n\004fro" +
      "m\030\002 \002(\t\022(\n\tmatchroom\030\003 \001(\0132\025.Gate2Match_" +
      "MatchRoomB%\n\034com.wangboo.cluster.protoco" +
      "lB\005Proto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_P2CenterJoinRoom_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_P2CenterJoinRoom_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_P2CenterJoinRoom_descriptor,
              new java.lang.String[] { "RoomNo", },
              com.wangboo.cluster.protocol.Proto.P2CenterJoinRoom.class,
              com.wangboo.cluster.protocol.Proto.P2CenterJoinRoom.Builder.class);
          internal_static_P2CenterMsg_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_P2CenterMsg_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_P2CenterMsg_descriptor,
              new java.lang.String[] { "MsgId", "From", "RoleId", "JoinRoom", },
              com.wangboo.cluster.protocol.Proto.P2CenterMsg.class,
              com.wangboo.cluster.protocol.Proto.P2CenterMsg.Builder.class);
          internal_static_Gate2Match_MatchRoom_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_Gate2Match_MatchRoom_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Gate2Match_MatchRoom_descriptor,
              new java.lang.String[] { "Roleid", "Name", "Gold", },
              com.wangboo.cluster.protocol.Proto.Gate2Match_MatchRoom.class,
              com.wangboo.cluster.protocol.Proto.Gate2Match_MatchRoom.Builder.class);
          internal_static_Gate2MatchMsg_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_Gate2MatchMsg_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Gate2MatchMsg_descriptor,
              new java.lang.String[] { "MsgId", "From", "Matchroom", },
              com.wangboo.cluster.protocol.Proto.Gate2MatchMsg.class,
              com.wangboo.cluster.protocol.Proto.Gate2MatchMsg.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.wangboo.cluster.protocol.MsgIdProto.getDescriptor(),
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
